export const demoResources = [
  {
    id: 1,
    title: "Recycled Aluminum Sheets",
    category: "metal",
    seller: "EcoRenew Pvt. Ltd.",
    sellerType: "industry",
    location: "Pune, Maharashtra",
    price: 180,
    stock: 500,
    certified: true,
    ecoPoints: 50,
    icon: "🔩",
    description: "High-quality recycled aluminum sheets suitable for construction and manufacturing.",
  },
  {
    id: 2,
    title: "PET Plastic Pellets",
    category: "plastic",
    seller: "GreenCycle India",
    sellerType: "industry",
    location: "Mumbai, Maharashtra",
    price: 90,
    stock: 1200,
    certified: true,
    ecoPoints: 25,
    icon: "♻️",
    description: "Recycled PET plastic pellets for packaging and textile applications.",
  },
  {
    id: 3,
    title: "Recycled Kraft Paper",
    category: "paper",
    seller: "RePaper Hub",
    sellerType: "individual",
    location: "Delhi, NCR",
    price: 55,
    stock: 2000,
    certified: true,
    ecoPoints: 15,
    icon: "📄",
    description: "Eco-friendly recycled kraft paper for packaging and printing.",
  },
  {
    id: 4,
    title: "Copper Extract from E-Waste",
    category: "e-waste",
    seller: "EWaste India Pvt Ltd",
    sellerType: "industry",
    location: "Bangalore, Karnataka",
    price: 560,
    stock: 300,
    certified: true,
    ecoPoints: 140,
    icon: "🔌",
    description: "Pure copper extracted from recycled electronic waste.",
  },
  {
    id: 5,
    title: "Organic Compost",
    category: "compost",
    seller: "Indore Compost Facility",
    sellerType: "ngo",
    location: "Indore, Madhya Pradesh",
    price: 20,
    stock: 1500,
    certified: true,
    ecoPoints: 5,
    icon: "🌱",
    description: "Nutrient-rich organic compost for agriculture and gardening.",
  },
  {
    id: 6,
    title: "Recycled Steel Rods",
    category: "metal",
    seller: "SteelCycle Industries",
    sellerType: "industry",
    location: "Kolkata, West Bengal",
    price: 220,
    stock: 400,
    certified: true,
    ecoPoints: 55,
    icon: "🏗️",
    description: "High-strength recycled steel rods for construction projects.",
  },
  {
    id: 7,
    title: "Recycled Textile Fibers",
    category: "textile",
    seller: "FabricRenew Co.",
    sellerType: "industry",
    location: "Tiruppur, Tamil Nadu",
    price: 150,
    stock: 600,
    certified: true,
    ecoPoints: 37,
    icon: "🧵",
    description: "Recycled textile fibers for clothing and home furnishing.",
  },
  {
    id: 8,
    title: "Plastic Waste Pellets",
    category: "plastic",
    seller: "PlasticCycle Ltd",
    sellerType: "industry",
    location: "Surat, Gujarat",
    price: 75,
    stock: 1800,
    certified: false,
    ecoPoints: 18,
    icon: "♻️",
    description: "Recycled plastic waste pellets for various applications.",
  },
  {
    id: 9,
    title: "Recycled Glass Cullet",
    category: "metal",
    seller: "GlassRenew Industries",
    sellerType: "industry",
    location: "Jaipur, Rajasthan",
    price: 120,
    stock: 800,
    certified: true,
    ecoPoints: 30,
    icon: "🔷",
    description: "Recycled glass cullet for glass manufacturing and construction.",
  },
  {
    id: 10,
    title: "Cardboard Waste Sheets",
    category: "paper",
    seller: "CardboardCycle",
    sellerType: "individual",
    location: "Ahmedabad, Gujarat",
    price: 40,
    stock: 2500,
    certified: true,
    ecoPoints: 10,
    icon: "📦",
    description: "Recycled cardboard sheets for packaging and crafts.",
  },
  {
    id: 11,
    title: "Rubber Crumb from Tires",
    category: "plastic",
    seller: "RubberRecycle Pro",
    sellerType: "industry",
    location: "Chennai, Tamil Nadu",
    price: 95,
    stock: 700,
    certified: true,
    ecoPoints: 23,
    icon: "🛞",
    description: "Recycled rubber crumb from old tires for various applications.",
  },
  {
    id: 12,
    title: "E-Waste Circuit Boards",
    category: "e-waste",
    seller: "CircuitRecycle Ltd",
    sellerType: "industry",
    location: "Hyderabad, Telangana",
    price: 450,
    stock: 250,
    certified: true,
    ecoPoints: 112,
    icon: "🖥️",
    description: "Recycled circuit boards from electronic waste for material recovery.",
  },
  {
    id: 13,
    title: "Recycled Plastic Bags",
    category: "plastic",
    seller: "BagRecycle Solutions",
    sellerType: "industry",
    location: "Bangalore, Karnataka",
    price: 65,
    stock: 3000,
    certified: true,
    ecoPoints: 16,
    icon: "🛍️",
    description: "Recycled plastic bags for retail and packaging use.",
  },
  {
    id: 14,
    title: "Organic Fertilizer",
    category: "compost",
    seller: "Green Harvest Farms",
    sellerType: "individual",
    location: "Nashik, Maharashtra",
    price: 35,
    stock: 2200,
    certified: true,
    ecoPoints: 8,
    icon: "🌾",
    description: "100% organic fertilizer from composted agricultural waste.",
  },
  {
    id: 15,
    title: "Recycled Copper Wire",
    category: "metal",
    seller: "MetalRecycle Pro",
    sellerType: "industry",
    location: "Vadodara, Gujarat",
    price: 380,
    stock: 450,
    certified: true,
    ecoPoints: 95,
    icon: "⚡",
    description: "High-purity recycled copper wire for electrical applications.",
  },
  {
    id: 16,
    title: "Biodegradable Packaging",
    category: "paper",
    seller: "EcoPackage India",
    sellerType: "industry",
    location: "Pune, Maharashtra",
    price: 120,
    stock: 1600,
    certified: true,
    ecoPoints: 30,
    icon: "📮",
    description: "100% biodegradable packaging materials for eco-conscious businesses.",
  },
  {
    id: 17,
    title: "Recycled Plastic Bottles",
    category: "plastic",
    seller: "BottleRecycle Ltd",
    sellerType: "industry",
    location: "Kolkata, West Bengal",
    price: 50,
    stock: 4000,
    certified: true,
    ecoPoints: 12,
    icon: "🍾",
    description: "Recycled plastic bottles suitable for beverage and storage use.",
  },
  {
    id: 18,
    title: "Recycled Aluminum Cans",
    category: "metal",
    seller: "CanRecycle Industries",
    sellerType: "industry",
    location: "Chennai, Tamil Nadu",
    price: 200,
    stock: 800,
    certified: true,
    ecoPoints: 50,
    icon: "🥫",
    description: "Recycled aluminum cans for beverage and food packaging.",
  },
  {
    id: 19,
    title: "Organic Cotton Fabric",
    category: "textile",
    seller: "Organic Textiles Co",
    sellerType: "industry",
    location: "Tiruppur, Tamil Nadu",
    price: 280,
    stock: 500,
    certified: true,
    ecoPoints: 70,
    icon: "👕",
    description: "Premium organic cotton fabric for apparel and home textiles.",
  },
  {
    id: 20,
    title: "Recycled Paper Pulp",
    category: "paper",
    seller: "PulpRecycle Hub",
    sellerType: "industry",
    location: "Lucknow, Uttar Pradesh",
    price: 45,
    stock: 2800,
    certified: true,
    ecoPoints: 11,
    icon: "📋",
    description: "Recycled paper pulp for paper manufacturing and packaging.",
  },
  {
    id: 21,
    title: "E-Waste Plastic Components",
    category: "e-waste",
    seller: "ElectroRecycle Ltd",
    sellerType: "industry",
    location: "Bangalore, Karnataka",
    price: 320,
    stock: 350,
    certified: true,
    ecoPoints: 80,
    icon: "🖲️",
    description: "Recycled plastic components from electronic waste.",
  },
  {
    id: 22,
    title: "Vermicompost",
    category: "compost",
    seller: "Worm Farm India",
    sellerType: "individual",
    location: "Pune, Maharashtra",
    price: 60,
    stock: 1200,
    certified: true,
    ecoPoints: 15,
    icon: "🪱",
    description: "Premium vermicompost for organic gardening and farming.",
  },
  {
    id: 23,
    title: "Recycled Plastic Lumber",
    category: "plastic",
    seller: "LumberRecycle Co",
    sellerType: "industry",
    location: "Surat, Gujarat",
    price: 250,
    stock: 600,
    certified: true,
    ecoPoints: 62,
    icon: "🪵",
    description: "Durable recycled plastic lumber for outdoor construction.",
  },
  {
    id: 24,
    title: "Recycled Stainless Steel",
    category: "metal",
    seller: "SteelRecycle Pro",
    sellerType: "industry",
    location: "Ahmedabad, Gujarat",
    price: 420,
    stock: 350,
    certified: true,
    ecoPoints: 105,
    icon: "🔧",
    description: "High-grade recycled stainless steel for industrial use.",
  },
  {
    id: 25,
    title: "Recycled Wool Fiber",
    category: "textile",
    seller: "WoolRecycle Industries",
    sellerType: "industry",
    location: "Ludhiana, Punjab",
    price: 320,
    stock: 400,
    certified: true,
    ecoPoints: 80,
    icon: "🧶",
    description: "Recycled wool fiber for textile and clothing applications.",
  },
  {
    id: 26,
    title: "Recycled Newspaper",
    category: "paper",
    seller: "NewsRecycle Hub",
    sellerType: "individual",
    location: "Delhi, NCR",
    price: 25,
    stock: 3500,
    certified: true,
    ecoPoints: 6,
    icon: "📰",
    description: "Recycled newspaper for packaging and craft applications.",
  },
  {
    id: 27,
    title: "E-Waste Gold Recovery",
    category: "e-waste",
    seller: "GoldRecycle Ltd",
    sellerType: "industry",
    location: "Hyderabad, Telangana",
    price: 2800,
    stock: 50,
    certified: true,
    ecoPoints: 700,
    icon: "💰",
    description: "Recovered gold from electronic waste for jewelry and electronics.",
  },
  {
    id: 28,
    title: "Biochar",
    category: "compost",
    seller: "Biochar Solutions",
    sellerType: "industry",
    location: "Indore, Madhya Pradesh",
    price: 150,
    stock: 800,
    certified: true,
    ecoPoints: 37,
    icon: "⚫",
    description: "Premium biochar for soil improvement and carbon sequestration.",
  },
  {
    id: 29,
    title: "Recycled Plastic Film",
    category: "plastic",
    seller: "FilmRecycle Industries",
    sellerType: "industry",
    location: "Mumbai, Maharashtra",
    price: 85,
    stock: 2200,
    certified: true,
    ecoPoints: 21,
    icon: "🎬",
    description: "Recycled plastic film for packaging and agricultural use.",
  },
  {
    id: 30,
    title: "Recycled Brass",
    category: "metal",
    seller: "BrassRecycle Co",
    sellerType: "industry",
    location: "Jamnagar, Gujarat",
    price: 480,
    stock: 280,
    certified: true,
    ecoPoints: 120,
    icon: "🎺",
    description: "High-quality recycled brass for industrial and decorative use.",
  },
  {
    id: 31,
    title: "Recycled Linen Fabric",
    category: "textile",
    seller: "LinenRecycle Co",
    sellerType: "industry",
    location: "Varanasi, Uttar Pradesh",
    price: 350,
    stock: 300,
    certified: true,
    ecoPoints: 87,
    icon: "🧵",
    description: "Recycled linen fabric for premium textile applications.",
  },
  {
    id: 32,
    title: "Recycled Cardboard Tubes",
    category: "paper",
    seller: "TubeRecycle Ltd",
    sellerType: "industry",
    location: "Bangalore, Karnataka",
    price: 35,
    stock: 2000,
    certified: true,
    ecoPoints: 8,
    icon: "🔄",
    description: "Recycled cardboard tubes for industrial and packaging use.",
  },
  {
    id: 33,
    title: "E-Waste Silver Recovery",
    category: "e-waste",
    seller: "SilverRecycle Pro",
    sellerType: "industry",
    location: "Pune, Maharashtra",
    price: 1200,
    stock: 100,
    certified: true,
    ecoPoints: 300,
    icon: "🥈",
    description: "Recovered silver from electronic waste for industrial use.",
  },
  {
    id: 34,
    title: "Peat-Free Compost",
    category: "compost",
    seller: "EcoCompost India",
    sellerType: "industry",
    location: "Nashik, Maharashtra",
    price: 55,
    stock: 1800,
    certified: true,
    ecoPoints: 13,
    icon: "🌍",
    description: "Sustainable peat-free compost for gardening and landscaping.",
  },
  {
    id: 35,
    title: "Recycled Plastic Granules",
    category: "plastic",
    seller: "GranuleRecycle Ltd",
    sellerType: "industry",
    location: "Surat, Gujarat",
    price: 70,
    stock: 3500,
    certified: true,
    ecoPoints: 17,
    icon: "⚪",
    description: "Recycled plastic granules for injection molding and extrusion.",
  },
  {
    id: 36,
    title: "Recycled Aluminum Foil",
    category: "metal",
    seller: "FoilRecycle Industries",
    sellerType: "industry",
    location: "Ahmedabad, Gujarat",
    price: 320,
    stock: 600,
    certified: true,
    ecoPoints: 80,
    icon: "🔶",
    description: "Recycled aluminum foil for packaging and insulation.",
  },
  {
    id: 37,
    title: "Recycled Polyester Fiber",
    category: "textile",
    seller: "PolyesterRecycle Co",
    sellerType: "industry",
    location: "Tiruppur, Tamil Nadu",
    price: 220,
    stock: 700,
    certified: true,
    ecoPoints: 55,
    icon: "🧥",
    description: "Recycled polyester fiber for apparel and home textiles.",
  },
  {
    id: 38,
    title: "Recycled Tissue Paper",
    category: "paper",
    seller: "TissueRecycle Hub",
    sellerType: "industry",
    location: "Lucknow, Uttar Pradesh",
    price: 40,
    stock: 2500,
    certified: true,
    ecoPoints: 10,
    icon: "🧻",
    description: "Recycled tissue paper for household and commercial use.",
  },
  {
    id: 39,
    title: "E-Waste Aluminum Recovery",
    category: "e-waste",
    seller: "AluminumRecycle Ltd",
    sellerType: "industry",
    location: "Bangalore, Karnataka",
    price: 280,
    stock: 400,
    certified: true,
    ecoPoints: 70,
    icon: "🛡️",
    description: "Recovered aluminum from electronic waste for manufacturing.",
  },
  {
    id: 40,
    title: "Mushroom Compost",
    category: "compost",
    seller: "Mushroom Farm India",
    sellerType: "individual",
    location: "Himachal Pradesh",
    price: 75,
    stock: 900,
    certified: true,
    ecoPoints: 18,
    icon: "🍄",
    description: "Premium mushroom compost for organic gardening.",
  },
]
