export const demoResources = [
  {
    id: 1,
    title: "Recycled Aluminum Sheets",
    category: "metal",
    seller: "EcoRenew Pvt. Ltd.",
    sellerType: "industry",
    location: "Pune, Maharashtra",
    price: 180,
    stock: 500,
    certified: true,
    ecoPoints: 50,
    icon: "🔩",
    description: "High-quality recycled aluminum sheets suitable for construction and manufacturing.",
  },
  {
    id: 2,
    title: "PET Plastic Pellets",
    category: "plastic",
    seller: "GreenCycle India",
    sellerType: "industry",
    location: "Mumbai, Maharashtra",
    price: 90,
    stock: 1200,
    certified: true,
    ecoPoints: 25,
    icon: "♻️",
    description: "Recycled PET plastic pellets for packaging and textile applications.",
  },
  {
    id: 3,
    title: "Recycled Kraft Paper",
    category: "paper",
    seller: "RePaper Hub",
    sellerType: "individual",
    location: "Delhi, NCR",
    price: 55,
    stock: 2000,
    certified: true,
    ecoPoints: 15,
    icon: "📄",
    description: "Eco-friendly recycled kraft paper for packaging and printing.",
  },
  {
    id: 4,
    title: "Copper Extract from E-Waste",
    category: "e-waste",
    seller: "EWaste India Pvt Ltd",
    sellerType: "industry",
    location: "Bangalore, Karnataka",
    price: 560,
    stock: 300,
    certified: true,
    ecoPoints: 140,
    icon: "🔌",
    description: "Pure copper extracted from recycled electronic waste.",
  },
  {
    id: 5,
    title: "Organic Compost",
    category: "compost",
    seller: "Indore Compost Facility",
    sellerType: "ngo",
    location: "Indore, Madhya Pradesh",
    price: 20,
    stock: 1500,
    certified: true,
    ecoPoints: 5,
    icon: "🌱",
    description: "Nutrient-rich organic compost for agriculture and gardening.",
  },
  {
    id: 6,
    title: "Recycled Steel Rods",
    category: "metal",
    seller: "SteelCycle Industries",
    sellerType: "industry",
    location: "Kolkata, West Bengal",
    price: 220,
    stock: 400,
    certified: true,
    ecoPoints: 55,
    icon: "🏗️",
    description: "High-strength recycled steel rods for construction projects.",
  },
  {
    id: 7,
    title: "Recycled Textile Fibers",
    category: "textile",
    seller: "FabricRenew Co.",
    sellerType: "industry",
    location: "Tiruppur, Tamil Nadu",
    price: 150,
    stock: 600,
    certified: true,
    ecoPoints: 37,
    icon: "🧵",
    description: "Recycled textile fibers for clothing and home furnishing.",
  },
  {
    id: 8,
    title: "Plastic Waste Pellets",
    category: "plastic",
    seller: "PlasticCycle Ltd",
    sellerType: "industry",
    location: "Surat, Gujarat",
    price: 75,
    stock: 1800,
    certified: false,
    ecoPoints: 18,
    icon: "♻️",
    description: "Recycled plastic waste pellets for various applications.",
  },
  {
    id: 9,
    title: "Recycled Glass Cullet",
    category: "metal",
    seller: "GlassRenew Industries",
    sellerType: "industry",
    location: "Jaipur, Rajasthan",
    price: 120,
    stock: 800,
    certified: true,
    ecoPoints: 30,
    icon: "🔷",
    description: "Recycled glass cullet for glass manufacturing and construction.",
  },
  {
    id: 10,
    title: "Cardboard Waste Sheets",
    category: "paper",
    seller: "CardboardCycle",
    sellerType: "individual",
    location: "Ahmedabad, Gujarat",
    price: 40,
    stock: 2500,
    certified: true,
    ecoPoints: 10,
    icon: "📦",
    description: "Recycled cardboard sheets for packaging and crafts.",
  },
  {
    id: 11,
    title: "Rubber Crumb from Tires",
    category: "plastic",
    seller: "RubberRecycle Pro",
    sellerType: "industry",
    location: "Chennai, Tamil Nadu",
    price: 95,
    stock: 700,
    certified: true,
    ecoPoints: 23,
    icon: "🛞",
    description: "Recycled rubber crumb from old tires for various applications.",
  },
  {
    id: 12,
    title: "E-Waste Circuit Boards",
    category: "e-waste",
    seller: "CircuitRecycle Ltd",
    sellerType: "industry",
    location: "Hyderabad, Telangana",
    price: 450,
    stock: 250,
    certified: true,
    ecoPoints: 112,
    icon: "🖥️",
    description: "Recycled circuit boards from electronic waste for material recovery.",
  },
]
