export const demoData = {
  nationalStats: {
    msw_tonnes_per_year: 62000000,
    lastWeek: {
      co2_saved_kg: 184500,
      trees_planted: 2847,
      plastic_recycled_kg: 156800,
      new_contributors: 12350,
      cities_engaged: 42,
    },
  },
  states: [
    {
      name: "Karnataka",
      region: "South",
      avgEcoPoints: 89.2,
      aiq: 92,
      waterPurity: 87,
      treesPerKm2: 42,
      populationM: 68,
    },
    {
      name: "Maharashtra",
      region: "West",
      avgEcoPoints: 85.4,
      aiq: 88,
      waterPurity: 80,
      treesPerKm2: 39,
      populationM: 123,
    },
    {
      name: "Madhya Pradesh",
      region: "Central",
      avgEcoPoints: 83.1,
      aiq: 84,
      waterPurity: 82,
      treesPerKm2: 33,
      populationM: 84,
    },
    {
      name: "Delhi",
      region: "North",
      avgEcoPoints: 78.6,
      aiq: 150,
      waterPurity: 65,
      treesPerKm2: 15,
      populationM: 30,
    },
    {
      name: "Tamil Nadu",
      region: "South",
      avgEcoPoints: 80.2,
      aiq: 98,
      waterPurity: 78,
      treesPerKm2: 22,
      populationM: 77,
    },
    {
      name: "Telangana",
      region: "South",
      avgEcoPoints: 82.8,
      aiq: 95,
      waterPurity: 81,
      treesPerKm2: 38,
      populationM: 39,
    },
    {
      name: "Andhra Pradesh",
      region: "South",
      avgEcoPoints: 81.5,
      aiq: 92,
      waterPurity: 79,
      treesPerKm2: 35,
      populationM: 50,
    },
    {
      name: "Gujarat",
      region: "West",
      avgEcoPoints: 79.3,
      aiq: 96,
      waterPurity: 76,
      treesPerKm2: 28,
      populationM: 61,
    },
    {
      name: "Rajasthan",
      region: "North",
      avgEcoPoints: 76.4,
      aiq: 102,
      waterPurity: 72,
      treesPerKm2: 18,
      populationM: 79,
    },
    {
      name: "Uttar Pradesh",
      region: "North",
      avgEcoPoints: 74.2,
      aiq: 128,
      waterPurity: 68,
      treesPerKm2: 16,
      populationM: 237,
    },
    {
      name: "West Bengal",
      region: "East",
      avgEcoPoints: 77.8,
      aiq: 105,
      waterPurity: 74,
      treesPerKm2: 31,
      populationM: 99,
    },
    {
      name: "Odisha",
      region: "East",
      avgEcoPoints: 80.6,
      aiq: 88,
      waterPurity: 83,
      treesPerKm2: 44,
      populationM: 47,
    },
    {
      name: "Jharkhand",
      region: "East",
      avgEcoPoints: 78.9,
      aiq: 91,
      waterPurity: 80,
      treesPerKm2: 40,
      populationM: 35,
    },
    {
      name: "Chhattisgarh",
      region: "Central",
      avgEcoPoints: 81.2,
      aiq: 86,
      waterPurity: 84,
      treesPerKm2: 45,
      populationM: 29,
    },
    {
      name: "Punjab",
      region: "North",
      avgEcoPoints: 75.1,
      aiq: 115,
      waterPurity: 70,
      treesPerKm2: 14,
      populationM: 28,
    },
    {
      name: "Haryana",
      region: "North",
      avgEcoPoints: 73.5,
      aiq: 135,
      waterPurity: 66,
      treesPerKm2: 12,
      populationM: 28,
    },
    {
      name: "Himachal Pradesh",
      region: "North",
      avgEcoPoints: 86.7,
      aiq: 72,
      waterPurity: 89,
      treesPerKm2: 52,
      populationM: 7,
    },
    {
      name: "Uttarakhand",
      region: "North",
      avgEcoPoints: 84.3,
      aiq: 78,
      waterPurity: 86,
      treesPerKm2: 48,
      populationM: 11,
    },
    {
      name: "Jammu & Kashmir",
      region: "North",
      avgEcoPoints: 85.1,
      aiq: 75,
      waterPurity: 88,
      treesPerKm2: 46,
      populationM: 13,
    },
    {
      name: "Kerala",
      region: "South",
      avgEcoPoints: 87.4,
      aiq: 85,
      waterPurity: 85,
      treesPerKm2: 41,
      populationM: 35,
    },
    {
      name: "Goa",
      region: "West",
      avgEcoPoints: 83.9,
      aiq: 82,
      waterPurity: 84,
      treesPerKm2: 37,
      populationM: 2,
    },
    {
      name: "Assam",
      region: "East",
      avgEcoPoints: 79.2,
      aiq: 93,
      waterPurity: 77,
      treesPerKm2: 36,
      populationM: 33,
    },
    {
      name: "Meghalaya",
      region: "East",
      avgEcoPoints: 82.5,
      aiq: 80,
      waterPurity: 87,
      treesPerKm2: 50,
      populationM: 3,
    },
    {
      name: "Manipur",
      region: "East",
      avgEcoPoints: 81.3,
      aiq: 79,
      waterPurity: 86,
      treesPerKm2: 49,
      populationM: 3,
    },
    {
      name: "Mizoram",
      region: "East",
      avgEcoPoints: 83.6,
      aiq: 76,
      waterPurity: 88,
      treesPerKm2: 51,
      populationM: 1,
    },
    {
      name: "Nagaland",
      region: "East",
      avgEcoPoints: 82.1,
      aiq: 77,
      waterPurity: 87,
      treesPerKm2: 48,
      populationM: 2,
    },
    {
      name: "Tripura",
      region: "East",
      avgEcoPoints: 80.8,
      aiq: 81,
      waterPurity: 85,
      treesPerKm2: 43,
      populationM: 4,
    },
    {
      name: "Sikkim",
      region: "East",
      avgEcoPoints: 88.9,
      aiq: 68,
      waterPurity: 91,
      treesPerKm2: 56,
      populationM: 1,
    },
  ],
}
