export const profilesDatabase = [
  // Top Tier Contributors (5000+ eco-points)
  {
    id: "anmol-sharma",
    name: "Anmol Sharma",
    email: "anmol.sharma@eco.in",
    phone: "+91 98765 43210",
    avatar: "AS",
    avatarColor: "from-blue-400 to-blue-600",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    bio: "Environmental technologist | Climate advocate | Building sustainable tech solutions",
    joinDate: "2021-01-15",
    ecoPoints: 5620,
    actions: 478,
    level: "Platinum",
    verified: true,
    badges: ["Eco Warrior", "Tech Innovator", "Community Leader", "Carbon Offset Master"],
    contributions: [
      "Solar Panel Installation",
      "E-waste Recycling",
      "Tree Planting",
      "Water Conservation",
      "Carbon Offsetting",
    ],
    socials: {
      twitter: "https://twitter.com/anmolsharma",
      linkedin: "https://linkedin.com/in/anmolsharma",
      instagram: "https://instagram.com/anmolsharma",
    },
    skills: ["Renewable Energy", "IoT Solutions", "Sustainability", "Climate Tech"],
    completedProjects: 47,
    referrals: 23,
    monthlyContribution: "2,450 kg CO2 saved",
    topContribution: "Solar Installation at 15 schools",
    impact: {
      carbonSaved: 12450,
      treesSaved: 890,
      plasticsRecycled: 5640,
      waterSaved: 125000,
    },
  },
  {
    id: "priya-desai",
    name: "Priya Desai",
    email: "priya.desai@eco.in",
    phone: "+91 98654 32109",
    avatar: "PD",
    avatarColor: "from-green-400 to-green-600",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    bio: "Sustainable fashion enthusiast | Reducing plastic footprint | Zero-waste lifestyle advocate",
    joinDate: "2020-06-20",
    ecoPoints: 5890,
    actions: 512,
    level: "Platinum",
    verified: true,
    badges: ["Zero Waste Hero", "Fashion Innovator", "Influencer", "Mentor"],
    contributions: ["Sustainable Fashion", "Plastic Reduction", "Upcycling", "Community Education", "Content Creation"],
    socials: {
      twitter: "https://twitter.com/priyadesai",
      linkedin: "https://linkedin.com/in/priyadesai",
      instagram: "https://instagram.com/priyadesai",
      youtube: "https://youtube.com/c/priyadesai",
    },
    skills: ["Fashion Design", "Sustainability", "Content Creation", "Public Speaking"],
    completedProjects: 52,
    referrals: 31,
    monthlyContribution: "2,890 kg CO2 saved",
    topContribution: "Sustainable Fashion Awareness Campaign - 50K reach",
    impact: {
      carbonSaved: 15230,
      treesSaved: 1120,
      plasticsRecycled: 8920,
      waterSaved: 185000,
    },
  },
  {
    id: "rajesh-patel",
    name: "Rajesh Patel",
    email: "rajesh.patel@eco.in",
    phone: "+91 98543 21098",
    avatar: "RP",
    avatarColor: "from-emerald-400 to-emerald-600",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    bio: "Water management expert | Agricultural consultant | Empowering rural communities",
    joinDate: "2021-03-10",
    ecoPoints: 5340,
    actions: 456,
    level: "Platinum",
    verified: true,
    badges: ["Water Expert", "Agricultural Leader", "Rural Champion", "Sustainability Builder"],
    contributions: ["Water Harvesting", "Organic Farming", "Soil Conservation", "Farmer Training", "Biodiversity"],
    socials: {
      linkedin: "https://linkedin.com/in/rajeshpatel",
      instagram: "https://instagram.com/rajeshpatel",
    },
    skills: ["Water Management", "Agriculture", "Rural Development", "Environmental Science"],
    completedProjects: 43,
    referrals: 18,
    monthlyContribution: "3,120 kg CO2 saved",
    topContribution: "Water Harvesting in 12 villages - Benefited 2000+ farmers",
    impact: {
      carbonSaved: 14560,
      treesSaved: 1340,
      plasticsRecycled: 2340,
      waterSaved: 250000,
    },
  },
  {
    id: "neha-gupta",
    name: "Neha Gupta",
    email: "neha.gupta@eco.in",
    phone: "+91 98432 10987",
    avatar: "NG",
    avatarColor: "from-pink-400 to-pink-600",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    bio: "Urban gardening expert | Compost champion | Green city developer",
    joinDate: "2021-11-05",
    ecoPoints: 5780,
    actions: 498,
    level: "Platinum",
    verified: true,
    badges: ["Gardening Master", "Compost Expert", "Urban Green Leader", "Community Educator"],
    contributions: ["Urban Gardening", "Composting", "Waste Management", "Green Building", "Education"],
    socials: {
      twitter: "https://twitter.com/nehagupta",
      instagram: "https://instagram.com/nehagupta",
      youtube: "https://youtube.com/c/nehagupta",
    },
    skills: ["Urban Agriculture", "Waste Management", "Education", "Community Building"],
    completedProjects: 48,
    referrals: 25,
    monthlyContribution: "2,650 kg CO2 saved",
    topContribution: "Created 500+ urban gardens - Reduced city waste by 25%",
    impact: {
      carbonSaved: 13890,
      treesSaved: 956,
      plasticsRecycled: 6780,
      waterSaved: 145000,
    },
  },
  {
    id: "vikram-singh",
    name: "Vikram Singh",
    email: "vikram.singh@eco.in",
    phone: "+91 98321 09876",
    avatar: "VS",
    avatarColor: "from-cyan-400 to-cyan-600",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    bio: "Renewable energy specialist | Solar power advocate | Sustainable business builder",
    joinDate: "2022-02-14",
    ecoPoints: 4950,
    actions: 412,
    level: "Gold",
    verified: true,
    badges: ["Solar Expert", "Energy Innovator", "Green Entrepreneur"],
    contributions: ["Solar Installation", "Renewable Energy", "Energy Efficiency", "Grid Integration"],
    socials: {
      linkedin: "https://linkedin.com/in/vikramsingh",
      twitter: "https://twitter.com/vikramsingh",
    },
    skills: ["Renewable Energy", "Engineering", "Business Development", "Technology"],
    completedProjects: 36,
    referrals: 14,
    monthlyContribution: "1,890 kg CO2 saved",
    topContribution: "Installed 500+ solar systems - Saved 25,000 tons CO2 annually",
    impact: {
      carbonSaved: 11230,
      treesSaved: 823,
      plasticsRecycled: 1240,
      waterSaved: 89000,
    },
  },

  // Gold Tier Contributors (3000-5000 eco-points)
  {
    id: "anjali-sharma",
    name: "Anjali Sharma",
    email: "anjali.sharma@eco.in",
    phone: "+91 98210 98765",
    avatar: "AS",
    avatarColor: "from-yellow-400 to-yellow-600",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    bio: "Environmental researcher | Climate scientist | Data-driven sustainability",
    joinDate: "2021-04-08",
    ecoPoints: 4680,
    actions: 389,
    level: "Gold",
    verified: true,
    badges: ["Research Expert", "Climate Scientist", "Data Analyst"],
    contributions: ["Climate Research", "Carbon Monitoring", "Environmental Impact Assessment"],
    socials: {
      linkedin: "https://linkedin.com/in/anjalisharm",
      twitter: "https://twitter.com/anjalisharm",
    },
    skills: ["Climate Science", "Data Analysis", "Research", "Environmental Science"],
    completedProjects: 28,
    referrals: 9,
    monthlyContribution: "1,450 kg CO2 measured",
    topContribution: "Climate impact research - Published 5 papers on carbon sequestration",
    impact: {
      carbonSaved: 8920,
      treesSaved: 567,
      plasticsRecycled: 3420,
      waterSaved: 76000,
    },
  },
  {
    id: "amit-verma",
    name: "Amit Verma",
    email: "amit.verma@eco.in",
    phone: "+91 98109 87654",
    avatar: "AV",
    avatarColor: "from-orange-400 to-orange-600",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    bio: "Tech entrepreneur | Green startup founder | Sustainability innovator",
    joinDate: "2021-05-22",
    ecoPoints: 4320,
    actions: 367,
    level: "Gold",
    verified: true,
    badges: ["Tech Entrepreneur", "Startup Founder", "Innovation Leader"],
    contributions: ["Tech Innovation", "Startup Ecosystem", "Green Solutions", "Mentorship"],
    socials: {
      linkedin: "https://linkedin.com/in/amitverma",
      twitter: "https://twitter.com/amitverma",
      website: "https://amitvermatech.com",
    },
    skills: ["Technology", "Business", "Innovation", "Mentoring"],
    completedProjects: 31,
    referrals: 16,
    monthlyContribution: "1,230 kg CO2 saved",
    topContribution: "Founded GreenTech startup - Serving 10K+ customers",
    impact: {
      carbonSaved: 9870,
      treesSaved: 701,
      plasticsRecycled: 4560,
      waterSaved: 95000,
    },
  },
  {
    id: "divya-nair",
    name: "Divya Nair",
    email: "divya.nair@eco.in",
    phone: "+91 97698 76543",
    avatar: "DN",
    avatarColor: "from-teal-400 to-teal-600",
    city: "Kochi",
    state: "Kerala",
    country: "India",
    bio: "Marine conservation leader | Ocean researcher | Beach cleanup champion",
    joinDate: "2021-09-12",
    ecoPoints: 4520,
    actions: 412,
    level: "Gold",
    verified: true,
    badges: ["Ocean Guardian", "Marine Expert", "Conservation Leader"],
    contributions: ["Ocean Cleanup", "Marine Life Protection", "Beach Conservation", "Coral Protection"],
    socials: {
      instagram: "https://instagram.com/divyanair",
      twitter: "https://twitter.com/divyanair",
      youtube: "https://youtube.com/c/divyanair",
    },
    skills: ["Marine Biology", "Conservation", "Community Organizing", "Research"],
    completedProjects: 34,
    referrals: 12,
    monthlyContribution: "890 kg CO2 saved",
    topContribution: "Cleaned 50+ beaches - Removed 500 tons of plastic",
    impact: {
      carbonSaved: 7650,
      treesSaved: 432,
      plasticsRecycled: 12340,
      waterSaved: 65000,
    },
  },
  {
    id: "meera-singh",
    name: "Meera Singh",
    email: "meera.singh@eco.in",
    phone: "+91 97587 65432",
    avatar: "MS",
    avatarColor: "from-violet-400 to-violet-600",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    bio: "Educational advocate | School sustainability coordinator | Youth leader",
    joinDate: "2021-07-30",
    ecoPoints: 3890,
    actions: 345,
    level: "Gold",
    verified: true,
    badges: ["Education Champion", "Youth Leader", "Community Organizer"],
    contributions: ["School Programs", "Student Education", "Youth Engagement", "Curriculum Development"],
    socials: {
      linkedin: "https://linkedin.com/in/meerasingh",
      instagram: "https://instagram.com/meerasingh",
    },
    skills: ["Education", "Youth Development", "Community Work", "Program Management"],
    completedProjects: 25,
    referrals: 8,
    monthlyContribution: "1,120 kg CO2 saved",
    topContribution: "Trained 5000+ students in sustainability - 50 schools impacted",
    impact: {
      carbonSaved: 6780,
      treesSaved: 489,
      plasticsRecycled: 2890,
      waterSaved: 52000,
    },
  },
]

// Continue with Silver and Bronze tier...
export const silverTierProfiles = [
  {
    id: "arjun-kapoor",
    name: "Arjun Kapoor",
    email: "arjun.kapoor@eco.in",
    avatar: "AK",
    avatarColor: "from-indigo-400 to-indigo-600",
    city: "Lucknow",
    state: "Uttar Pradesh",
    bio: "Environmental educator and community organizer",
    ecoPoints: 2890,
    level: "Silver",
    verified: true,
  },
  {
    id: "sneha-bhat",
    name: "Sneha Bhat",
    email: "sneha.bhat@eco.in",
    avatar: "SB",
    avatarColor: "from-rose-400 to-rose-600",
    city: "Bangalore",
    state: "Karnataka",
    bio: "Sustainable lifestyle influencer and eco-blogger",
    ecoPoints: 3200,
    level: "Silver",
    verified: true,
  },
]

// Search-optimized flat list for quick lookups
export const allProfilesList = [
  ...profilesDatabase,
  ...silverTierProfiles,
  // Add more profiles as needed
]

// Export function for searching profiles
export function searchProfiles(query: string) {
  const lowerQuery = query.toLowerCase()
  return allProfilesList
    .filter(
      (profile) =>
        profile.name.toLowerCase().includes(lowerQuery) ||
        profile.city.toLowerCase().includes(lowerQuery) ||
        profile.state.toLowerCase().includes(lowerQuery) ||
        profile.bio.toLowerCase().includes(lowerQuery),
    )
    .slice(0, 8) // Return top 8 results
}

// Export function to get profile by ID
export function getProfileById(id: string) {
  return allProfilesList.find((profile) => profile.id === id)
}
