export const realData = {
  people: [
    // Tier 1: Top Contributors (Eco-Points 3000+)
    {
      id: "p1",
      name: "Rajesh Kumar",
      email: "rajesh.kumar@email.com",
      city: "Bangalore",
      state: "Karnataka",
      ecoPoints: 4850,
      actions: 356,
      joinDate: "2022-01-15",
      avatar: "RK",
      bio: "Environmental enthusiast and sustainability advocate",
      verified: true,
      contributions: ["Plastic Recycling", "Tree Planting", "Water Conservation", "Community Outreach"],
      level: "Platinum",
      badges: ["Eco Warrior", "Community Leader", "Recycling Champion"],
    },
    {
      id: "p2",
      name: "Priya Sharma",
      email: "priya.sharma@email.com",
      city: "Mumbai",
      state: "Maharashtra",
      ecoPoints: 5120,
      actions: 434,
      joinDate: "2021-06-20",
      avatar: "PS",
      bio: "Climate change researcher and green living advocate",
      verified: true,
      contributions: ["Carbon Offset", "Renewable Energy", "Sustainable Fashion", "Research"],
      level: "Platinum",
      badges: ["Climate Expert", "Researcher", "Influencer"],
    },
    {
      id: "p3",
      name: "Amit Patel",
      email: "amit.patel@email.com",
      city: "Ahmedabad",
      state: "Gujarat",
      ecoPoints: 3890,
      actions: 342,
      joinDate: "2022-03-10",
      avatar: "AP",
      bio: "Solar energy enthusiast and renewable energy expert",
      verified: true,
      contributions: ["Solar Installation", "Energy Efficiency", "Grid Integration"],
      level: "Gold",
      badges: ["Solar Expert", "Energy Saver"],
    },
    {
      id: "p4",
      name: "Neha Gupta",
      email: "neha.gupta@email.com",
      city: "Delhi",
      state: "Delhi",
      ecoPoints: 4780,
      actions: 398,
      joinDate: "2021-11-05",
      avatar: "NG",
      bio: "Urban gardening and composting expert",
      verified: true,
      contributions: ["Urban Gardening", "Composting", "Waste Management", "Education"],
      level: "Platinum",
      badges: ["Gardening Expert", "Waste Warrior"],
    },
    {
      id: "p5",
      name: "Vikram Singh",
      email: "vikram.singh@email.com",
      city: "Jaipur",
      state: "Rajasthan",
      ecoPoints: 3100,
      actions: 267,
      joinDate: "2022-02-14",
      avatar: "VS",
      bio: "Water conservation specialist and hydrologist",
      verified: true,
      contributions: ["Water Harvesting", "Irrigation Optimization", "Watershed Management"],
      level: "Gold",
      badges: ["Water Expert", "Conservation Leader"],
    },
    {
      id: "p6",
      name: "Anjali Desai",
      email: "anjali.desai@email.com",
      city: "Pune",
      state: "Maharashtra",
      ecoPoints: 5450,
      actions: 467,
      joinDate: "2021-04-08",
      avatar: "AD",
      bio: "Sustainable agriculture promoter and farmer",
      verified: true,
      contributions: ["Organic Farming", "Soil Health", "Biodiversity", "Farmer Training"],
      level: "Platinum",
      badges: ["Agriculture Expert", "Biodiversity Champion"],
    },
    {
      id: "p7",
      name: "Rohan Verma",
      email: "rohan.verma@email.com",
      city: "Hyderabad",
      state: "Telangana",
      ecoPoints: 3340,
      actions: 276,
      joinDate: "2022-05-22",
      avatar: "RV",
      bio: "Tech enthusiast for green solutions and IoT developer",
      verified: true,
      contributions: ["Smart Energy", "IoT Solutions", "Tech Innovation"],
      level: "Gold",
      badges: ["Tech Innovator", "Smart Solutions"],
    },
    {
      id: "p8",
      name: "Divya Nair",
      email: "divya.nair@email.com",
      city: "Kochi",
      state: "Kerala",
      ecoPoints: 4950,
      actions: 412,
      joinDate: "2021-09-12",
      avatar: "DN",
      bio: "Marine conservation advocate and ocean researcher",
      verified: true,
      contributions: ["Ocean Cleanup", "Marine Life Protection", "Beach Conservation"],
      level: "Platinum",
      badges: ["Ocean Guardian", "Marine Expert"],
    },
    {
      id: "p9",
      name: "Sanjay Reddy",
      email: "sanjay.reddy@email.com",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      ecoPoints: 2750,
      actions: 228,
      joinDate: "2022-07-03",
      avatar: "SR",
      bio: "Renewable energy consultant and engineer",
      verified: true,
      contributions: ["Wind Energy", "Solar Power", "Energy Consulting"],
      level: "Silver",
      badges: ["Energy Expert"],
    },
    {
      id: "p10",
      name: "Meera Iyer",
      email: "meera.iyer@email.com",
      city: "Chennai",
      state: "Tamil Nadu",
      ecoPoints: 4620,
      actions: 389,
      joinDate: "2021-12-01",
      avatar: "MI",
      bio: "Waste reduction and recycling expert",
      verified: true,
      contributions: ["Recycling Programs", "Zero Waste Living", "Waste Audit"],
      level: "Platinum",
      badges: ["Recycling Champion", "Zero Waste Expert"],
    },
    // Tier 2: Active Contributors (Eco-Points 2000-3000)
    {
      id: "p11",
      name: "Arjun Kapoor",
      email: "arjun.kapoor@email.com",
      city: "Lucknow",
      state: "Uttar Pradesh",
      ecoPoints: 2920,
      actions: 245,
      joinDate: "2022-04-18",
      avatar: "AK",
      bio: "Environmental educator and school coordinator",
      verified: true,
      contributions: ["Education", "Awareness", "Youth Programs"],
      level: "Silver",
      badges: ["Educator"],
    },
    {
      id: "p12",
      name: "Sneha Bhat",
      email: "sneha.bhat@email.com",
      city: "Bangalore",
      state: "Karnataka",
      ecoPoints: 3200,
      actions: 245,
      joinDate: "2021-08-25",
      avatar: "SB",
      bio: "Sustainable lifestyle blogger and influencer",
      verified: true,
      contributions: ["Sustainable Fashion", "Eco-friendly Products", "Content Creation"],
      level: "Gold",
      badges: ["Influencer", "Lifestyle Expert"],
    },
    {
      id: "p13",
      name: "Karan Malhotra",
      email: "karan.malhotra@email.com",
      city: "Gurgaon",
      state: "Haryana",
      ecoPoints: 2650,
      actions: 198,
      joinDate: "2022-09-10",
      avatar: "KM",
      bio: "Corporate sustainability manager",
      verified: true,
      contributions: ["Corporate Sustainability", "Green Office", "Employee Engagement"],
      level: "Silver",
      badges: ["Corporate Leader"],
    },
    {
      id: "p14",
      name: "Pooja Verma",
      email: "pooja.verma@email.com",
      city: "Indore",
      state: "Madhya Pradesh",
      ecoPoints: 2780,
      actions: 212,
      joinDate: "2022-06-15",
      avatar: "PV",
      bio: "Community organizer and NGO coordinator",
      verified: true,
      contributions: ["Community Programs", "NGO Work", "Volunteer Coordination"],
      level: "Silver",
      badges: ["Community Leader"],
    },
    {
      id: "p15",
      name: "Rahul Nair",
      email: "rahul.nair@email.com",
      city: "Cochin",
      state: "Kerala",
      ecoPoints: 2450,
      actions: 176,
      joinDate: "2022-10-20",
      avatar: "RN",
      bio: "Renewable energy installer",
      verified: true,
      contributions: ["Solar Installation", "Wind Energy", "Energy Audit"],
      level: "Silver",
      badges: ["Energy Installer"],
    },
    {
      id: "p16",
      name: "Deepa Sharma",
      email: "deepa.sharma@email.com",
      city: "Chandigarh",
      state: "Punjab",
      ecoPoints: 2890,
      actions: 234,
      joinDate: "2022-03-05",
      avatar: "DS",
      bio: "Organic farmer and agricultural consultant",
      verified: true,
      contributions: ["Organic Farming", "Farmer Training", "Soil Conservation"],
      level: "Silver",
      badges: ["Agriculture Expert"],
    },
    {
      id: "p17",
      name: "Nikhil Deshmukh",
      email: "nikhil.deshmukh@email.com",
      city: "Nagpur",
      state: "Maharashtra",
      ecoPoints: 2560,
      actions: 189,
      joinDate: "2022-07-12",
      avatar: "ND",
      bio: "Waste management specialist",
      verified: true,
      contributions: ["Waste Management", "Recycling", "Landfill Reduction"],
      level: "Silver",
      badges: ["Waste Expert"],
    },
    {
      id: "p18",
      name: "Isha Patel",
      email: "isha.patel@email.com",
      city: "Surat",
      state: "Gujarat",
      ecoPoints: 2720,
      actions: 205,
      joinDate: "2022-05-08",
      avatar: "IP",
      bio: "Textile sustainability expert",
      verified: true,
      contributions: ["Sustainable Textiles", "Fashion Industry", "Waste Reduction"],
      level: "Silver",
      badges: ["Textile Expert"],
    },
    {
      id: "p19",
      name: "Vikrant Joshi",
      email: "vikrant.joshi@email.com",
      city: "Pune",
      state: "Maharashtra",
      ecoPoints: 2340,
      actions: 167,
      joinDate: "2022-08-30",
      avatar: "VJ",
      bio: "Water treatment engineer",
      verified: true,
      contributions: ["Water Treatment", "Wastewater Management", "Water Recycling"],
      level: "Silver",
      badges: ["Water Engineer"],
    },
    {
      id: "p20",
      name: "Ananya Singh",
      email: "ananya.singh@email.com",
      city: "Noida",
      state: "Uttar Pradesh",
      ecoPoints: 2610,
      actions: 195,
      joinDate: "2022-04-22",
      avatar: "AS",
      bio: "Environmental lawyer and policy advocate",
      verified: true,
      contributions: ["Policy Advocacy", "Legal Support", "Environmental Rights"],
      level: "Silver",
      badges: ["Legal Expert"],
    },
    // Tier 3: Growing Contributors (Eco-Points 1000-2000)
    {
      id: "p21",
      name: "Suresh Kumar",
      email: "suresh.kumar@email.com",
      city: "Coimbatore",
      state: "Tamil Nadu",
      ecoPoints: 1850,
      actions: 134,
      joinDate: "2023-01-10",
      avatar: "SK",
      bio: "Local environmental activist",
      verified: true,
      contributions: ["Tree Planting", "Community Cleanup"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p22",
      name: "Priya Nair",
      email: "priya.nair@email.com",
      city: "Thrissur",
      state: "Kerala",
      ecoPoints: 1620,
      actions: 112,
      joinDate: "2023-02-15",
      avatar: "PN",
      bio: "Sustainable living enthusiast",
      verified: true,
      contributions: ["Sustainable Living", "Eco-friendly Products"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p23",
      name: "Arun Verma",
      email: "arun.verma@email.com",
      city: "Vadodara",
      state: "Gujarat",
      ecoPoints: 1920,
      actions: 145,
      joinDate: "2022-12-20",
      avatar: "AV",
      bio: "Green building enthusiast",
      verified: true,
      contributions: ["Green Building", "Energy Efficiency"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p24",
      name: "Kavya Reddy",
      email: "kavya.reddy@email.com",
      city: "Secunderabad",
      state: "Telangana",
      ecoPoints: 1750,
      actions: 128,
      joinDate: "2023-03-05",
      avatar: "KR",
      bio: "Plastic-free living advocate",
      verified: true,
      contributions: ["Plastic Reduction", "Zero Waste"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p25",
      name: "Ravi Shankar",
      email: "ravi.shankar@email.com",
      city: "Bhopal",
      state: "Madhya Pradesh",
      ecoPoints: 1680,
      actions: 118,
      joinDate: "2023-01-25",
      avatar: "RS",
      bio: "Urban farmer",
      verified: true,
      contributions: ["Urban Gardening", "Food Production"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p26",
      name: "Nisha Gupta",
      email: "nisha.gupta@email.com",
      city: "Jaipur",
      state: "Rajasthan",
      ecoPoints: 1540,
      actions: 105,
      joinDate: "2023-02-10",
      avatar: "NG",
      bio: "Environmental blogger",
      verified: true,
      contributions: ["Content Creation", "Awareness"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p27",
      name: "Mohit Sharma",
      email: "mohit.sharma@email.com",
      city: "Ludhiana",
      state: "Punjab",
      ecoPoints: 1890,
      actions: 142,
      joinDate: "2022-11-30",
      avatar: "MS",
      bio: "Renewable energy enthusiast",
      verified: true,
      contributions: ["Solar Energy", "Energy Awareness"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p28",
      name: "Shreya Patel",
      email: "shreya.patel@email.com",
      city: "Rajkot",
      state: "Gujarat",
      ecoPoints: 1720,
      actions: 125,
      joinDate: "2023-03-18",
      avatar: "SP",
      bio: "Sustainable fashion enthusiast",
      verified: true,
      contributions: ["Sustainable Fashion", "Upcycling"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p29",
      name: "Arjun Singh",
      email: "arjun.singh@email.com",
      city: "Ranchi",
      state: "Jharkhand",
      ecoPoints: 1650,
      actions: 115,
      joinDate: "2023-02-28",
      avatar: "AS",
      bio: "Forest conservation volunteer",
      verified: true,
      contributions: ["Forest Conservation", "Tree Planting"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p30",
      name: "Divya Sharma",
      email: "divya.sharma@email.com",
      city: "Patna",
      state: "Bihar",
      ecoPoints: 1580,
      actions: 108,
      joinDate: "2023-03-12",
      avatar: "DS",
      bio: "Water conservation advocate",
      verified: true,
      contributions: ["Water Conservation", "Rainwater Harvesting"],
      level: "Bronze",
      badges: [],
    },
    // Additional 20+ contributors for diversity
    {
      id: "p31",
      name: "Vikram Patel",
      email: "vikram.patel@email.com",
      city: "Gandhinagar",
      state: "Gujarat",
      ecoPoints: 1450,
      actions: 98,
      joinDate: "2023-04-05",
      avatar: "VP",
      bio: "Green technology enthusiast",
      verified: false,
      contributions: ["Technology", "Innovation"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p32",
      name: "Anjali Verma",
      email: "anjali.verma@email.com",
      city: "Indore",
      state: "Madhya Pradesh",
      ecoPoints: 1380,
      actions: 92,
      joinDate: "2023-04-15",
      avatar: "AV",
      bio: "Community volunteer",
      verified: false,
      contributions: ["Community Work"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p33",
      name: "Rohan Desai",
      email: "rohan.desai@email.com",
      city: "Nashik",
      state: "Maharashtra",
      ecoPoints: 1520,
      actions: 102,
      joinDate: "2023-03-25",
      avatar: "RD",
      bio: "Agricultural innovator",
      verified: true,
      contributions: ["Agriculture", "Innovation"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p34",
      name: "Priya Desai",
      email: "priya.desai@email.com",
      city: "Aurangabad",
      state: "Maharashtra",
      ecoPoints: 1410,
      actions: 95,
      joinDate: "2023-04-20",
      avatar: "PD",
      bio: "Environmental educator",
      verified: false,
      contributions: ["Education"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p35",
      name: "Sanjay Verma",
      email: "sanjay.verma@email.com",
      city: "Amritsar",
      state: "Punjab",
      ecoPoints: 1640,
      actions: 118,
      joinDate: "2023-02-08",
      avatar: "SV",
      bio: "Waste management volunteer",
      verified: true,
      contributions: ["Waste Management"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p36",
      name: "Neha Sharma",
      email: "neha.sharma@email.com",
      city: "Shimla",
      state: "Himachal Pradesh",
      ecoPoints: 1290,
      actions: 85,
      joinDate: "2023-05-01",
      avatar: "NS",
      bio: "Mountain conservation advocate",
      verified: false,
      contributions: ["Conservation"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p37",
      name: "Amit Desai",
      email: "amit.desai@email.com",
      city: "Srinagar",
      state: "Jammu and Kashmir",
      ecoPoints: 1360,
      actions: 90,
      joinDate: "2023-04-10",
      avatar: "AD",
      bio: "Local environmental activist",
      verified: false,
      contributions: ["Local Activism"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p38",
      name: "Kavya Nair",
      email: "kavya.nair@email.com",
      city: "Thiruvananthapuram",
      state: "Kerala",
      ecoPoints: 1500,
      actions: 100,
      joinDate: "2023-03-30",
      avatar: "KN",
      bio: "Sustainable living blogger",
      verified: true,
      contributions: ["Blogging", "Awareness"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p39",
      name: "Rahul Verma",
      email: "rahul.verma@email.com",
      city: "Guwahati",
      state: "Assam",
      ecoPoints: 1420,
      actions: 96,
      joinDate: "2023-04-12",
      avatar: "RV",
      bio: "Biodiversity enthusiast",
      verified: false,
      contributions: ["Biodiversity"],
      level: "Bronze",
      badges: [],
    },
    {
      id: "p40",
      name: "Pooja Sharma",
      email: "pooja.sharma@email.com",
      city: "Bhubaneswar",
      state: "Odisha",
      ecoPoints: 1350,
      actions: 88,
      joinDate: "2023-04-25",
      avatar: "PS",
      bio: "Coastal conservation volunteer",
      verified: false,
      contributions: ["Coastal Conservation"],
      level: "Bronze",
      badges: [],
    },
  ],

  industries: [
    // Tier 1: Top Industries
    {
      id: "ind1",
      name: "GreenTech Solutions",
      sector: "Technology",
      location: "Bangalore, Karnataka",
      ecoPoints: 25000,
      employees: 450,
      certifications: ["ISO 14001", "B Corp Certified", "Carbon Neutral"],
      initiatives: ["Carbon Neutral Operations", "Renewable Energy", "Waste Reduction", "Green IT"],
      verified: true,
      rating: 4.9,
      description: "Leading provider of sustainable technology solutions",
      founded: 2015,
      website: "greentech.example.com",
    },
    {
      id: "ind2",
      name: "EcoManufacture Ltd",
      sector: "Manufacturing",
      location: "Pune, Maharashtra",
      ecoPoints: 22500,
      employees: 320,
      certifications: ["ISO 14001", "Green Factory Certified", "Zero Waste"],
      initiatives: ["Water Recycling", "Energy Efficiency", "Sustainable Materials", "Circular Economy"],
      verified: true,
      rating: 4.8,
      description: "Sustainable manufacturing with zero-waste commitment",
      founded: 2012,
      website: "ecomanufacture.example.com",
    },
    {
      id: "ind3",
      name: "Solar Power India",
      sector: "Energy",
      location: "Hyderabad, Telangana",
      ecoPoints: 28000,
      employees: 280,
      certifications: ["ISO 9001", "Renewable Energy Certified", "Grid Certified"],
      initiatives: ["Solar Installation", "Grid Integration", "Community Projects", "Energy Storage"],
      verified: true,
      rating: 4.9,
      description: "India's leading solar energy provider",
      founded: 2010,
      website: "solarpower.example.com",
    },
    {
      id: "ind4",
      name: "Organic Harvest Farms",
      sector: "Agriculture",
      location: "Nashik, Maharashtra",
      ecoPoints: 21000,
      employees: 150,
      certifications: ["Organic Certified", "Fair Trade", "Biodiversity Certified"],
      initiatives: ["Organic Farming", "Soil Health", "Biodiversity", "Farmer Training"],
      verified: true,
      rating: 4.8,
      description: "Premium organic agricultural products",
      founded: 2008,
      website: "organicharvest.example.com",
    },
    {
      id: "ind5",
      name: "CleanWater Systems",
      sector: "Water Management",
      location: "Delhi",
      ecoPoints: 23500,
      employees: 200,
      certifications: ["Water Quality Certified", "ISO 14001", "WHO Approved"],
      initiatives: ["Water Purification", "Rainwater Harvesting", "Wastewater Treatment", "Water Audit"],
      verified: true,
      rating: 4.8,
      description: "Advanced water treatment and conservation solutions",
      founded: 2014,
      website: "cleanwater.example.com",
    },
    {
      id: "ind6",
      name: "EcoPackaging Co",
      sector: "Packaging",
      location: "Ahmedabad, Gujarat",
      ecoPoints: 19500,
      employees: 180,
      certifications: ["Eco-Friendly Packaging", "ISO 14001", "Biodegradable Certified"],
      initiatives: ["Biodegradable Materials", "Recycling Programs", "Plastic Reduction"],
      verified: true,
      rating: 4.7,
      description: "Sustainable packaging solutions for businesses",
      founded: 2016,
      website: "ecopackaging.example.com",
    },
    {
      id: "ind7",
      name: "Green Building Corp",
      sector: "Construction",
      location: "Mumbai, Maharashtra",
      ecoPoints: 24200,
      employees: 380,
      certifications: ["LEED Certified", "Green Building Certified", "Energy Star"],
      initiatives: ["Sustainable Construction", "Energy Efficient Buildings", "Green Spaces"],
      verified: true,
      rating: 4.9,
      description: "Eco-friendly construction and real estate development",
      founded: 2011,
      website: "greenbuilding.example.com",
    },
    {
      id: "ind8",
      name: "Renewable Textiles",
      sector: "Textiles",
      location: "Tiruppur, Tamil Nadu",
      ecoPoints: 20800,
      employees: 220,
      certifications: ["Organic Textile Certified", "Fair Trade", "Water Efficient"],
      initiatives: ["Sustainable Fabrics", "Waste Reduction", "Water Conservation", "Dye Recycling"],
      verified: true,
      rating: 4.8,
      description: "Sustainable textile manufacturing",
      founded: 2013,
      website: "renewabletextiles.example.com",
    },
    {
      id: "ind9",
      name: "EcoTransport Solutions",
      sector: "Transportation",
      location: "Bangalore, Karnataka",
      ecoPoints: 22000,
      employees: 290,
      certifications: ["Electric Vehicle Certified", "Carbon Neutral", "ISO 14001"],
      initiatives: ["EV Fleet", "Route Optimization", "Emission Reduction", "Green Logistics"],
      verified: true,
      rating: 4.8,
      description: "Sustainable transportation and logistics",
      founded: 2015,
      website: "ecotransport.example.com",
    },
    {
      id: "ind10",
      name: "Green Hospitality Group",
      sector: "Hospitality",
      location: "Goa",
      ecoPoints: 18900,
      employees: 150,
      certifications: ["Green Hotel Certified", "ISO 14001", "Eco-Tourism Certified"],
      initiatives: ["Energy Efficiency", "Waste Management", "Community Engagement", "Water Conservation"],
      verified: true,
      rating: 4.7,
      description: "Eco-friendly hospitality and tourism services",
      founded: 2017,
      website: "greenhotel.example.com",
    },
    // Additional 40+ industries
    {
      id: "ind11",
      name: "WindPower Innovations",
      sector: "Energy",
      location: "Chennai, Tamil Nadu",
      ecoPoints: 21500,
      employees: 210,
      certifications: ["Wind Energy Certified", "ISO 14001"],
      initiatives: ["Wind Turbine Installation", "Energy Generation", "Community Benefits"],
      verified: true,
      rating: 4.7,
      description: "Wind energy solutions provider",
      founded: 2014,
      website: "windpower.example.com",
    },
    {
      id: "ind12",
      name: "Biotech Innovations",
      sector: "Biotechnology",
      location: "Bangalore, Karnataka",
      ecoPoints: 19800,
      employees: 165,
      certifications: ["Biotech Certified", "ISO 14001"],
      initiatives: ["Sustainable Biotech", "Green Chemistry", "Waste Reduction"],
      verified: true,
      rating: 4.6,
      description: "Sustainable biotechnology research and development",
      founded: 2016,
      website: "biotech.example.com",
    },
    {
      id: "ind13",
      name: "Eco Fashion Hub",
      sector: "Fashion",
      location: "Delhi",
      ecoPoints: 17500,
      employees: 120,
      certifications: ["Sustainable Fashion Certified", "Fair Trade"],
      initiatives: ["Sustainable Fashion", "Ethical Production", "Waste Reduction"],
      verified: true,
      rating: 4.5,
      description: "Sustainable fashion and apparel company",
      founded: 2018,
      website: "ecofashion.example.com",
    },
    {
      id: "ind14",
      name: "Organic Foods India",
      sector: "Food & Beverage",
      location: "Pune, Maharashtra",
      ecoPoints: 20200,
      employees: 180,
      certifications: ["Organic Certified", "Fair Trade", "Sustainable Agriculture"],
      initiatives: ["Organic Production", "Sustainable Farming", "Community Support"],
      verified: true,
      rating: 4.7,
      description: "Organic food production and distribution",
      founded: 2012,
      website: "organicfoods.example.com",
    },
    {
      id: "ind15",
      name: "Waste Management Pro",
      sector: "Waste Management",
      location: "Bangalore, Karnataka",
      ecoPoints: 18700,
      employees: 140,
      certifications: ["Waste Management Certified", "ISO 14001"],
      initiatives: ["Waste Segregation", "Recycling", "Landfill Reduction"],
      verified: true,
      rating: 4.6,
      description: "Professional waste management services",
      founded: 2015,
      website: "wastemanagement.example.com",
    },
    {
      id: "ind16",
      name: "Green Chemicals Ltd",
      sector: "Chemicals",
      location: "Mumbai, Maharashtra",
      ecoPoints: 19300,
      employees: 175,
      certifications: ["Green Chemistry Certified", "ISO 14001"],
      initiatives: ["Eco-Friendly Chemicals", "Waste Reduction", "Safe Production"],
      verified: true,
      rating: 4.6,
      description: "Sustainable chemical manufacturing",
      founded: 2013,
      website: "greenchemicals.example.com",
    },
    {
      id: "ind17",
      name: "Renewable Energy Consulting",
      sector: "Consulting",
      location: "Hyderabad, Telangana",
      ecoPoints: 17200,
      employees: 95,
      certifications: ["Energy Consulting Certified", "ISO 14001"],
      initiatives: ["Energy Audit", "Renewable Energy Planning", "Sustainability Consulting"],
      verified: true,
      rating: 4.5,
      description: "Renewable energy consulting services",
      founded: 2016,
      website: "renewableconsulting.example.com",
    },
    {
      id: "ind18",
      name: "Eco Tourism Operators",
      sector: "Tourism",
      location: "Goa",
      ecoPoints: 16800,
      employees: 110,
      certifications: ["Eco-Tourism Certified", "Sustainable Tourism"],
      initiatives: ["Eco-Tourism", "Community Engagement", "Conservation"],
      verified: true,
      rating: 4.5,
      description: "Sustainable tourism and eco-adventure services",
      founded: 2017,
      website: "ecotourism.example.com",
    },
    {
      id: "ind19",
      name: "Smart City Solutions",
      sector: "Technology",
      location: "Pune, Maharashtra",
      ecoPoints: 20500,
      employees: 200,
      certifications: ["Smart City Certified", "ISO 14001"],
      initiatives: ["Smart Infrastructure", "Energy Efficiency", "Sustainable Cities"],
      verified: true,
      rating: 4.7,
      description: "Smart city technology and solutions",
      founded: 2015,
      website: "smartcity.example.com",
    },
    {
      id: "ind20",
      name: "Biodiversity Conservation",
      sector: "Conservation",
      location: "Bangalore, Karnataka",
      ecoPoints: 19000,
      employees: 130,
      certifications: ["Conservation Certified", "Biodiversity Certified"],
      initiatives: ["Wildlife Protection", "Habitat Restoration", "Research"],
      verified: true,
      rating: 4.6,
      description: "Biodiversity conservation and research organization",
      founded: 2010,
      website: "biodiversity.example.com",
    },
    // More industries for comprehensive coverage
    {
      id: "ind21",
      name: "Sustainable Agriculture Tech",
      sector: "AgriTech",
      location: "Nashik, Maharashtra",
      ecoPoints: 18500,
      employees: 125,
      certifications: ["AgriTech Certified", "Sustainable Farming"],
      initiatives: ["Precision Agriculture", "Water Efficiency", "Soil Health"],
      verified: true,
      rating: 4.6,
      description: "Agricultural technology for sustainable farming",
      founded: 2016,
      website: "agritech.example.com",
    },
    {
      id: "ind22",
      name: "Eco Education Foundation",
      sector: "Education",
      location: "Delhi",
      ecoPoints: 15800,
      employees: 85,
      certifications: ["Education Certified", "Environmental Education"],
      initiatives: ["Environmental Education", "Awareness Programs", "Youth Training"],
      verified: true,
      rating: 4.5,
      description: "Environmental education and awareness foundation",
      founded: 2014,
      website: "ecoeducation.example.com",
    },
    {
      id: "ind23",
      name: "Green Finance Solutions",
      sector: "Finance",
      location: "Mumbai, Maharashtra",
      ecoPoints: 20800,
      employees: 160,
      certifications: ["Green Finance Certified", "ESG Certified"],
      initiatives: ["Green Financing", "Sustainable Investments", "ESG Reporting"],
      verified: true,
      rating: 4.7,
      description: "Green finance and sustainable investment solutions",
      founded: 2015,
      website: "greenfinance.example.com",
    },
    {
      id: "ind24",
      name: "Plastic Alternatives Co",
      sector: "Manufacturing",
      location: "Ahmedabad, Gujarat",
      ecoPoints: 19200,
      employees: 145,
      certifications: ["Plastic Alternatives Certified", "ISO 14001"],
      initiatives: ["Plastic Alternatives", "Biodegradable Products", "Waste Reduction"],
      verified: true,
      rating: 4.6,
      description: "Manufacturer of plastic alternatives and biodegradable products",
      founded: 2017,
      website: "plasticalternatives.example.com",
    },
    {
      id: "ind25",
      name: "Carbon Offset Services",
      sector: "Environmental Services",
      location: "Bangalore, Karnataka",
      ecoPoints: 21300,
      employees: 110,
      certifications: ["Carbon Offset Certified", "ISO 14001"],
      initiatives: ["Carbon Offsetting", "Reforestation", "Emission Reduction"],
      verified: true,
      rating: 4.7,
      description: "Carbon offset and climate action services",
      founded: 2014,
      website: "carbonoffset.example.com",
    },
    {
      id: "ind26",
      name: "Renewable Energy Storage",
      sector: "Energy",
      location: "Hyderabad, Telangana",
      ecoPoints: 22100,
      employees: 190,
      certifications: ["Energy Storage Certified", "ISO 14001"],
      initiatives: ["Battery Storage", "Grid Stability", "Energy Management"],
      verified: true,
      rating: 4.8,
      description: "Renewable energy storage solutions",
      founded: 2016,
      website: "energystorage.example.com",
    },
    {
      id: "ind27",
      name: "Sustainable Supply Chain",
      sector: "Logistics",
      location: "Chennai, Tamil Nadu",
      ecoPoints: 19800,
      employees: 155,
      certifications: ["Supply Chain Certified", "ISO 14001"],
      initiatives: ["Sustainable Logistics", "Emission Reduction", "Efficiency"],
      verified: true,
      rating: 4.6,
      description: "Sustainable supply chain and logistics solutions",
      founded: 2015,
      website: "sustainablesupply.example.com",
    },
    {
      id: "ind28",
      name: "Green Building Materials",
      sector: "Construction",
      location: "Pune, Maharashtra",
      ecoPoints: 18900,
      employees: 135,
      certifications: ["Green Materials Certified", "ISO 14001"],
      initiatives: ["Eco-Friendly Materials", "Sustainable Construction", "Waste Reduction"],
      verified: true,
      rating: 4.6,
      description: "Sustainable building materials supplier",
      founded: 2014,
      website: "greenmaterials.example.com",
    },
    {
      id: "ind29",
      name: "Water Recycling Systems",
      sector: "Water Management",
      location: "Delhi",
      ecoPoints: 20600,
      employees: 140,
      certifications: ["Water Recycling Certified", "ISO 14001"],
      initiatives: ["Water Recycling", "Wastewater Treatment", "Water Conservation"],
      verified: true,
      rating: 4.7,
      description: "Advanced water recycling and treatment systems",
      founded: 2013,
      website: "waterrecycling.example.com",
    },
    {
      id: "ind30",
      name: "Eco Certification Services",
      sector: "Certification",
      location: "Bangalore, Karnataka",
      ecoPoints: 17500,
      employees: 100,
      certifications: ["Certification Certified", "ISO 14001"],
      initiatives: ["Eco Certification", "Sustainability Audits", "Compliance"],
      verified: true,
      rating: 4.5,
      description: "Environmental certification and compliance services",
      founded: 2015,
      website: "ecocertification.example.com",
    },
  ],

  resources: [
    // Premium Resources (High Eco-Impact)
    {
      id: "r1",
      name: "Recycled Plastic Pellets",
      category: "Raw Materials",
      seller: "EcoManufacture Ltd",
      price: 45,
      quantity: 1000,
      unit: "kg",
      location: "Pune, Maharashtra",
      certified: true,
      rating: 4.9,
      description: "High-quality recycled plastic pellets for manufacturing",
      ecoImpact: "Reduces plastic waste by 500kg per batch",
      inStock: 5000,
      reviews: 234,
    },
    {
      id: "r2",
      name: "Organic Fertilizer",
      category: "Agricultural",
      seller: "Organic Harvest Farms",
      price: 25,
      quantity: 50,
      unit: "kg",
      location: "Nashik, Maharashtra",
      certified: true,
      rating: 4.9,
      description: "100% organic fertilizer from composted waste",
      ecoImpact: "Improves soil health and reduces chemical usage",
      inStock: 8000,
      reviews: 456,
    },
    {
      id: "r3",
      name: "Solar Panel (500W)",
      category: "Energy",
      seller: "Solar Power India",
      price: 15000,
      quantity: 1,
      unit: "piece",
      location: "Hyderabad, Telangana",
      certified: true,
      rating: 4.9,
      description: "High-efficiency monocrystalline solar panel",
      ecoImpact: "Generates 2000 kWh annually, saves 2 tons CO2/year",
      inStock: 500,
      reviews: 789,
    },
    {
      id: "r4",
      name: "Biodegradable Packaging",
      category: "Packaging",
      seller: "EcoPackaging Co",
      price: 120,
      quantity: 500,
      unit: "pieces",
      location: "Ahmedabad, Gujarat",
      certified: true,
      rating: 4.8,
      description: "100% biodegradable packaging materials",
      ecoImpact: "Reduces plastic waste by 250kg per order",
      inStock: 3000,
      reviews: 567,
    },
    {
      id: "r5",
      name: "Water Purification System",
      category: "Water Management",
      seller: "CleanWater Systems",
      price: 8500,
      quantity: 1,
      unit: "piece",
      location: "Delhi",
      certified: true,
      rating: 4.8,
      description: "Advanced water purification for homes and offices",
      ecoImpact: "Saves 10,000 liters of water annually",
      inStock: 200,
      reviews: 345,
    },
    {
      id: "r6",
      name: "Organic Cotton Fabric",
      category: "Textiles",
      seller: "Renewable Textiles",
      price: 350,
      quantity: 10,
      unit: "meters",
      location: "Tiruppur, Tamil Nadu",
      certified: true,
      rating: 4.9,
      description: "Premium organic cotton fabric for apparel",
      ecoImpact: "Uses 91% less water than conventional cotton",
      inStock: 1500,
      reviews: 678,
    },
    {
      id: "r7",
      name: "LED Lighting Kit",
      category: "Energy",
      seller: "GreenTech Solutions",
      price: 2500,
      quantity: 1,
      unit: "kit",
      location: "Bangalore, Karnataka",
      certified: true,
      rating: 4.8,
      description: "Complete LED lighting solution for offices",
      ecoImpact: "Reduces energy consumption by 80%",
      inStock: 800,
      reviews: 456,
    },
    {
      id: "r8",
      name: "Rainwater Harvesting Kit",
      category: "Water Management",
      seller: "CleanWater Systems",
      price: 12000,
      quantity: 1,
      unit: "piece",
      location: "Delhi",
      certified: true,
      rating: 4.9,
      description: "Complete rainwater harvesting system",
      ecoImpact: "Collects 50,000 liters annually",
      inStock: 150,
      reviews: 234,
    },
    {
      id: "r9",
      name: "Eco-Friendly Paint",
      category: "Building Materials",
      seller: "Green Building Corp",
      price: 800,
      quantity: 20,
      unit: "liters",
      location: "Mumbai, Maharashtra",
      certified: true,
      rating: 4.7,
      description: "Zero-VOC eco-friendly paint for interiors",
      ecoImpact: "No harmful emissions, safe for health",
      inStock: 2000,
      reviews: 345,
    },
    {
      id: "r10",
      name: "Bamboo Flooring",
      category: "Building Materials",
      seller: "Green Building Corp",
      price: 450,
      quantity: 1,
      unit: "sq.meter",
      location: "Mumbai, Maharashtra",
      certified: true,
      rating: 4.9,
      description: "Sustainable bamboo flooring material",
      ecoImpact: "Bamboo grows 35x faster than trees",
      inStock: 3000,
      reviews: 567,
    },
    // Additional 40+ resources for comprehensive marketplace
    {
      id: "r11",
      name: "Recycled Aluminum Sheets",
      category: "Raw Materials",
      seller: "EcoManufacture Ltd",
      price: 180,
      quantity: 500,
      unit: "kg",
      location: "Pune, Maharashtra",
      certified: true,
      rating: 4.8,
      description: "High-quality recycled aluminum sheets",
      ecoImpact: "Saves 95% energy compared to virgin aluminum",
      inStock: 2000,
      reviews: 234,
    },
    {
      id: "r12",
      name: "PET Plastic Pellets",
      category: "Raw Materials",
      seller: "GreenCycle India",
      price: 90,
      quantity: 1200,
      unit: "kg",
      location: "Mumbai, Maharashtra",
      certified: true,
      rating: 4.7,
      description: "Recycled PET plastic pellets",
      ecoImpact: "Reduces plastic waste significantly",
      inStock: 5000,
      reviews: 345,
    },
    {
      id: "r13",
      name: "Recycled Kraft Paper",
      category: "Packaging",
      seller: "RePaper Hub",
      price: 55,
      quantity: 2000,
      unit: "sheets",
      location: "Delhi, NCR",
      certified: true,
      rating: 4.6,
      description: "Eco-friendly recycled kraft paper",
      ecoImpact: "100% recyclable and biodegradable",
      inStock: 8000,
      reviews: 456,
    },
    {
      id: "r14",
      name: "Copper Extract from E-Waste",
      category: "Raw Materials",
      seller: "EWaste India Pvt Ltd",
      price: 560,
      quantity: 300,
      unit: "kg",
      location: "Bangalore, Karnataka",
      certified: true,
      rating: 4.8,
      description: "Pure copper extracted from recycled e-waste",
      ecoImpact: "Prevents e-waste from landfills",
      inStock: 1000,
      reviews: 234,
    },
    {
      id: "r15",
      name: "Organic Compost",
      category: "Agricultural",
      seller: "Indore Compost Facility",
      price: 20,
      quantity: 1500,
      unit: "kg",
      location: "Indore, Madhya Pradesh",
      certified: true,
      rating: 4.7,
      description: "Nutrient-rich organic compost",
      ecoImpact: "Improves soil quality naturally",
      inStock: 10000,
      reviews: 567,
    },
    {
      id: "r16",
      name: "Recycled Steel Rods",
      category: "Raw Materials",
      seller: "SteelCycle Industries",
      price: 220,
      quantity: 400,
      unit: "kg",
      location: "Kolkata, West Bengal",
      certified: true,
      rating: 4.8,
      description: "High-strength recycled steel rods",
      ecoImpact: "Reduces mining impact",
      inStock: 2000,
      reviews: 345,
    },
    {
      id: "r17",
      name: "Recycled Textile Fibers",
      category: "Textiles",
      seller: "FabricRenew Co.",
      price: 150,
      quantity: 600,
      unit: "kg",
      location: "Tiruppur, Tamil Nadu",
      certified: true,
      rating: 4.8,
      description: "Recycled textile fibers for clothing",
      ecoImpact: "Reduces textile waste",
      inStock: 3000,
      reviews: 456,
    },
    {
      id: "r18",
      name: "Plastic Waste Pellets",
      category: "Raw Materials",
      seller: "PlasticCycle Ltd",
      price: 75,
      quantity: 1800,
      unit: "kg",
      location: "Surat, Gujarat",
      certified: false,
      rating: 4.5,
      description: "Recycled plastic waste pellets",
      ecoImpact: "Diverts plastic from landfills",
      inStock: 6000,
      reviews: 234,
    },
    {
      id: "r19",
      name: "Recycled Glass Cullet",
      category: "Raw Materials",
      seller: "GlassRenew Industries",
      price: 120,
      quantity: 800,
      unit: "kg",
      location: "Jaipur, Rajasthan",
      certified: true,
      rating: 4.7,
      description: "Recycled glass cullet for manufacturing",
      ecoImpact: "Saves energy in glass production",
      inStock: 4000,
      reviews: 345,
    },
    {
      id: "r20",
      name: "Cardboard Waste Sheets",
      category: "Packaging",
      seller: "CardboardCycle",
      price: 40,
      quantity: 2500,
      unit: "sheets",
      location: "Ahmedabad, Gujarat",
      certified: true,
      rating: 4.6,
      description: "Recycled cardboard sheets",
      ecoImpact: "100% recyclable",
      inStock: 10000,
      reviews: 567,
    },
    // Continue with more resources...
    {
      id: "r21",
      name: "Rubber Crumb from Tires",
      category: "Raw Materials",
      seller: "RubberRecycle Pro",
      price: 95,
      quantity: 700,
      unit: "kg",
      location: "Chennai, Tamil Nadu",
      certified: true,
      rating: 4.7,
      description: "Recycled rubber crumb from old tires",
      ecoImpact: "Prevents tire waste",
      inStock: 3500,
      reviews: 234,
    },
    {
      id: "r22",
      name: "E-Waste Circuit Boards",
      category: "Raw Materials",
      seller: "CircuitRecycle Ltd",
      price: 450,
      quantity: 250,
      unit: "kg",
      location: "Hyderabad, Telangana",
      certified: true,
      rating: 4.8,
      description: "Recycled circuit boards from e-waste",
      ecoImpact: "Recovers valuable materials",
      inStock: 1200,
      reviews: 345,
    },
    {
      id: "r23",
      name: "Recycled Plastic Bags",
      category: "Packaging",
      seller: "BagRecycle Solutions",
      price: 65,
      quantity: 3000,
      unit: "pieces",
      location: "Bangalore, Karnataka",
      certified: true,
      rating: 4.6,
      description: "Recycled plastic bags for retail",
      ecoImpact: "Reduces single-use plastic",
      inStock: 15000,
      reviews: 456,
    },
    {
      id: "r24",
      name: "Organic Fertilizer Premium",
      category: "Agricultural",
      seller: "Green Harvest Farms",
      price: 35,
      quantity: 2200,
      unit: "kg",
      location: "Nashik, Maharashtra",
      certified: true,
      rating: 4.8,
      description: "Premium organic fertilizer",
      ecoImpact: "100% natural and sustainable",
      inStock: 8000,
      reviews: 567,
    },
    {
      id: "r25",
      name: "Recycled Copper Wire",
      category: "Raw Materials",
      seller: "MetalRecycle Pro",
      price: 380,
      quantity: 450,
      unit: "kg",
      location: "Vadodara, Gujarat",
      certified: true,
      rating: 4.8,
      description: "High-purity recycled copper wire",
      ecoImpact: "Reduces mining impact",
      inStock: 2000,
      reviews: 345,
    },
    {
      id: "r26",
      name: "Biodegradable Packaging Premium",
      category: "Packaging",
      seller: "EcoPackage India",
      price: 120,
      quantity: 1600,
      unit: "pieces",
      location: "Pune, Maharashtra",
      certified: true,
      rating: 4.9,
      description: "Premium biodegradable packaging",
      ecoImpact: "Completely compostable",
      inStock: 5000,
      reviews: 678,
    },
    {
      id: "r27",
      name: "Recycled Plastic Bottles",
      category: "Packaging",
      seller: "BottleRecycle Ltd",
      price: 50,
      quantity: 4000,
      unit: "pieces",
      location: "Kolkata, West Bengal",
      certified: true,
      rating: 4.7,
      description: "Recycled plastic bottles",
      ecoImpact: "Diverts bottles from landfills",
      inStock: 20000,
      reviews: 456,
    },
    {
      id: "r28",
      name: "Recycled Aluminum Cans",
      category: "Raw Materials",
      seller: "CanRecycle Industries",
      price: 200,
      quantity: 800,
      unit: "kg",
      location: "Chennai, Tamil Nadu",
      certified: true,
      rating: 4.8,
      description: "Recycled aluminum cans",
      ecoImpact: "Saves 95% energy",
      inStock: 4000,
      reviews: 345,
    },
    {
      id: "r29",
      name: "Organic Cotton Fabric Premium",
      category: "Textiles",
      seller: "Organic Textiles Co",
      price: 280,
      quantity: 500,
      unit: "meters",
      location: "Tiruppur, Tamil Nadu",
      certified: true,
      rating: 4.9,
      description: "Premium organic cotton fabric",
      ecoImpact: "Water-efficient production",
      inStock: 2000,
      reviews: 567,
    },
    {
      id: "r30",
      name: "Recycled Paper Pulp",
      category: "Packaging",
      seller: "PulpRecycle Hub",
      price: 45,
      quantity: 2800,
      unit: "kg",
      location: "Lucknow, Uttar Pradesh",
      certified: true,
      rating: 4.6,
      description: "Recycled paper pulp",
      ecoImpact: "Reduces deforestation",
      inStock: 10000,
      reviews: 234,
    },
    // Add 20+ more resources for comprehensive marketplace
    {
      id: "r31",
      name: "E-Waste Plastic Components",
      category: "Raw Materials",
      seller: "ElectroRecycle Ltd",
      price: 320,
      quantity: 350,
      unit: "kg",
      location: "Bangalore, Karnataka",
      certified: true,
      rating: 4.7,
      description: "Recycled plastic from e-waste",
      ecoImpact: "Prevents e-waste pollution",
      inStock: 1500,
      reviews: 345,
    },
    {
      id: "r32",
      name: "Vermicompost",
      category: "Agricultural",
      seller: "Worm Farm India",
      price: 60,
      quantity: 1200,
      unit: "kg",
      location: "Pune, Maharashtra",
      certified: true,
      rating: 4.8,
      description: "Premium vermicompost",
      ecoImpact: "Improves soil naturally",
      inStock: 5000,
      reviews: 456,
    },
    {
      id: "r33",
      name: "Recycled Plastic Lumber",
      category: "Building Materials",
      seller: "LumberRecycle Co",
      price: 250,
      quantity: 600,
      unit: "pieces",
      location: "Surat, Gujarat",
      certified: true,
      rating: 4.7,
      description: "Durable recycled plastic lumber",
      ecoImpact: "Prevents deforestation",
      inStock: 3000,
      reviews: 234,
    },
    {
      id: "r34",
      name: "Recycled Stainless Steel",
      category: "Raw Materials",
      seller: "SteelRecycle Pro",
      price: 420,
      quantity: 350,
      unit: "kg",
      location: "Ahmedabad, Gujarat",
      certified: true,
      rating: 4.8,
      description: "High-grade recycled stainless steel",
      ecoImpact: "Reduces mining impact",
      inStock: 2000,
      reviews: 345,
    },
    {
      id: "r35",
      name: "Recycled Wool Fiber",
      category: "Textiles",
      seller: "WoolRecycle Industries",
      price: 320,
      quantity: 400,
      unit: "kg",
      location: "Ludhiana, Punjab",
      certified: true,
      rating: 4.8,
      description: "Recycled wool fiber",
      ecoImpact: "Reduces textile waste",
      inStock: 2000,
      reviews: 456,
    },
    {
      id: "r36",
      name: "Recycled Newspaper",
      category: "Packaging",
      seller: "NewsRecycle Hub",
      price: 25,
      quantity: 3500,
      unit: "kg",
      location: "Delhi, NCR",
      certified: true,
      rating: 4.5,
      description: "Recycled newspaper",
      ecoImpact: "Reduces paper waste",
      inStock: 15000,
      reviews: 234,
    },
    {
      id: "r37",
      name: "E-Waste Gold Recovery",
      category: "Raw Materials",
      seller: "GoldRecycle Ltd",
      price: 2800,
      quantity: 50,
      unit: "grams",
      location: "Hyderabad, Telangana",
      certified: true,
      rating: 4.9,
      description: "Recovered gold from e-waste",
      ecoImpact: "Prevents e-waste pollution",
      inStock: 500,
      reviews: 567,
    },
    {
      id: "r38",
      name: "Biochar",
      category: "Agricultural",
      seller: "Biochar Solutions",
      price: 150,
      quantity: 800,
      unit: "kg",
      location: "Indore, Madhya Pradesh",
      certified: true,
      rating: 4.8,
      description: "Premium biochar",
      ecoImpact: "Carbon sequestration",
      inStock: 4000,
      reviews: 345,
    },
    {
      id: "r39",
      name: "Recycled Plastic Film",
      category: "Packaging",
      seller: "FilmRecycle Industries",
      price: 85,
      quantity: 2200,
      unit: "kg",
      location: "Mumbai, Maharashtra",
      certified: true,
      rating: 4.6,
      description: "Recycled plastic film",
      ecoImpact: "Reduces plastic waste",
      inStock: 8000,
      reviews: 234,
    },
    {
      id: "r40",
      name: "Recycled Brass",
      category: "Raw Materials",
      seller: "BrassRecycle Co",
      price: 480,
      quantity: 280,
      unit: "kg",
      location: "Jamnagar, Gujarat",
      certified: true,
      rating: 4.8,
      description: "High-quality recycled brass",
      ecoImpact: "Reduces mining impact",
      inStock: 1500,
      reviews: 345,
    },
    {
      id: "r41",
      name: "Recycled Linen Fabric",
      category: "Textiles",
      seller: "LinenRecycle Co",
      price: 350,
      quantity: 300,
      unit: "meters",
      location: "Varanasi, Uttar Pradesh",
      certified: true,
      rating: 4.8,
      description: "Recycled linen fabric",
      ecoImpact: "Water-efficient production",
      inStock: 1500,
      reviews: 456,
    },
    {
      id: "r42",
      name: "Recycled Cardboard Tubes",
      category: "Packaging",
      seller: "TubeRecycle Ltd",
      price: 35,
      quantity: 2000,
      unit: "pieces",
      location: "Bangalore, Karnataka",
      certified: true,
      rating: 4.5,
      description: "Recycled cardboard tubes",
      ecoImpact: "100% recyclable",
      inStock: 10000,
      reviews: 234,
    },
    {
      id: "r43",
      name: "E-Waste Silver Recovery",
      category: "Raw Materials",
      seller: "SilverRecycle Pro",
      price: 1200,
      quantity: 100,
      unit: "grams",
      location: "Pune, Maharashtra",
      certified: true,
      rating: 4.8,
      description: "Recovered silver from e-waste",
      ecoImpact: "Prevents e-waste pollution",
      inStock: 800,
      reviews: 345,
    },
    {
      id: "r44",
      name: "Peat-Free Compost",
      category: "Agricultural",
      seller: "EcoCompost India",
      price: 55,
      quantity: 1800,
      unit: "kg",
      location: "Nashik, Maharashtra",
      certified: true,
      rating: 4.7,
      description: "Sustainable peat-free compost",
      ecoImpact: "Protects peatlands",
      inStock: 6000,
      reviews: 456,
    },
    {
      id: "r45",
      name: "Recycled Plastic Granules",
      category: "Raw Materials",
      seller: "GranuleRecycle Ltd",
      price: 70,
      quantity: 3500,
      unit: "kg",
      location: "Surat, Gujarat",
      certified: true,
      rating: 4.6,
      description: "Recycled plastic granules",
      ecoImpact: "Reduces plastic waste",
      inStock: 15000,
      reviews: 234,
    },
    {
      id: "r46",
      name: "Recycled Aluminum Foil",
      category: "Raw Materials",
      seller: "FoilRecycle Industries",
      price: 320,
      quantity: 600,
      unit: "kg",
      location: "Ahmedabad, Gujarat",
      certified: true,
      rating: 4.7,
      description: "Recycled aluminum foil",
      ecoImpact: "Saves energy",
      inStock: 3000,
      reviews: 345,
    },
    {
      id: "r47",
      name: "Recycled Polyester Fiber",
      category: "Textiles",
      seller: "PolyesterRecycle Co",
      price: 220,
      quantity: 700,
      unit: "kg",
      location: "Tiruppur, Tamil Nadu",
      certified: true,
      rating: 4.7,
      description: "Recycled polyester fiber",
      ecoImpact: "Reduces textile waste",
      inStock: 3500,
      reviews: 456,
    },
    {
      id: "r48",
      name: "Recycled Tissue Paper",
      category: "Packaging",
      seller: "TissueRecycle Hub",
      price: 40,
      quantity: 2500,
      unit: "kg",
      location: "Lucknow, Uttar Pradesh",
      certified: true,
      rating: 4.5,
      description: "Recycled tissue paper",
      ecoImpact: "Reduces paper waste",
      inStock: 10000,
      reviews: 234,
    },
    {
      id: "r49",
      name: "E-Waste Aluminum Recovery",
      category: "Raw Materials",
      seller: "AluminumRecycle Ltd",
      price: 280,
      quantity: 400,
      unit: "kg",
      location: "Bangalore, Karnataka",
      certified: true,
      rating: 4.7,
      description: "Recovered aluminum from e-waste",
      ecoImpact: "Prevents e-waste pollution",
      inStock: 2000,
      reviews: 345,
    },
    {
      id: "r50",
      name: "Mushroom Compost",
      category: "Agricultural",
      seller: "Mushroom Farm India",
      price: 75,
      quantity: 900,
      unit: "kg",
      location: "Himachal Pradesh",
      certified: true,
      rating: 4.8,
      description: "Premium mushroom compost",
      ecoImpact: "Improves soil naturally",
      inStock: 4000,
      reviews: 456,
    },
  ],

  searchableData: {
    people: [
      "Rajesh Kumar",
      "Priya Sharma",
      "Amit Patel",
      "Neha Gupta",
      "Vikram Singh",
      "Anjali Desai",
      "Rohan Verma",
      "Divya Nair",
      "Sanjay Reddy",
      "Meera Iyer",
      "Arjun Kapoor",
      "Sneha Bhat",
      "Karan Malhotra",
      "Pooja Verma",
      "Rahul Nair",
      "Deepa Sharma",
      "Nikhil Deshmukh",
      "Isha Patel",
      "Vikrant Joshi",
      "Ananya Singh",
      "Suresh Kumar",
      "Priya Nair",
      "Arun Verma",
      "Kavya Reddy",
      "Ravi Shankar",
      "Nisha Gupta",
      "Mohit Sharma",
      "Shreya Patel",
      "Arjun Singh",
      "Divya Sharma",
    ],
    industries: [
      "GreenTech Solutions",
      "EcoManufacture Ltd",
      "Solar Power India",
      "Organic Harvest Farms",
      "CleanWater Systems",
      "EcoPackaging Co",
      "Green Building Corp",
      "Renewable Textiles",
      "EcoTransport Solutions",
      "Green Hospitality Group",
      "WindPower Innovations",
      "Biotech Innovations",
      "Eco Fashion Hub",
      "Organic Foods India",
      "Waste Management Pro",
      "Green Chemicals Ltd",
      "Renewable Energy Consulting",
      "Eco Tourism Operators",
      "Smart City Solutions",
      "Biodiversity Conservation",
    ],
    states: [
      "Karnataka",
      "Maharashtra",
      "Gujarat",
      "Delhi",
      "Rajasthan",
      "Telangana",
      "Andhra Pradesh",
      "Tamil Nadu",
      "Uttar Pradesh",
      "Kerala",
      "Punjab",
      "Madhya Pradesh",
      "West Bengal",
      "Haryana",
      "Himachal Pradesh",
    ],
    cities: [
      "Bangalore",
      "Mumbai",
      "Ahmedabad",
      "Delhi",
      "Jaipur",
      "Pune",
      "Hyderabad",
      "Kochi",
      "Visakhapatnam",
      "Chennai",
      "Lucknow",
      "Nashik",
      "Tiruppur",
      "Goa",
      "Surat",
      "Vadodara",
      "Indore",
      "Chandigarh",
      "Nagpur",
      "Coimbatore",
    ],
  },
}
