export const realData = {
  // Real people/contributors data
  people: [
    {
      id: "p1",
      name: "Rajesh Kumar",
      email: "rajesh.kumar@email.com",
      city: "Bangalore",
      state: "Karnataka",
      ecoPoints: 2450,
      actions: 156,
      joinDate: "2023-01-15",
      avatar: "RK",
      bio: "Environmental enthusiast and sustainability advocate",
      verified: true,
      contributions: ["Plastic Recycling", "Tree Planting", "Water Conservation"],
    },
    {
      id: "p2",
      name: "Priya Sharma",
      email: "priya.sharma@email.com",
      city: "Mumbai",
      state: "Maharashtra",
      ecoPoints: 3120,
      actions: 234,
      joinDate: "2022-06-20",
      avatar: "PS",
      bio: "Climate change researcher and green living advocate",
      verified: true,
      contributions: ["Carbon Offset", "Renewable Energy", "Sustainable Fashion"],
    },
    {
      id: "p3",
      name: "Amit Patel",
      email: "amit.patel@email.com",
      city: "Ahmedabad",
      state: "Gujarat",
      ecoPoints: 1890,
      actions: 142,
      joinDate: "2023-03-10",
      avatar: "AP",
      bio: "Solar energy enthusiast",
      verified: true,
      contributions: ["Solar Installation", "Energy Efficiency"],
    },
    {
      id: "p4",
      name: "Neha Gupta",
      email: "neha.gupta@email.com",
      city: "Delhi",
      state: "Delhi",
      ecoPoints: 2780,
      actions: 198,
      joinDate: "2022-11-05",
      avatar: "NG",
      bio: "Urban gardening and composting expert",
      verified: true,
      contributions: ["Urban Gardening", "Composting", "Waste Management"],
    },
    {
      id: "p5",
      name: "Vikram Singh",
      email: "vikram.singh@email.com",
      city: "Jaipur",
      state: "Rajasthan",
      ecoPoints: 2100,
      actions: 167,
      joinDate: "2023-02-14",
      avatar: "VS",
      bio: "Water conservation specialist",
      verified: true,
      contributions: ["Water Harvesting", "Irrigation Optimization"],
    },
    {
      id: "p6",
      name: "Anjali Desai",
      email: "anjali.desai@email.com",
      city: "Pune",
      state: "Maharashtra",
      ecoPoints: 3450,
      actions: 267,
      joinDate: "2022-04-08",
      avatar: "AD",
      bio: "Sustainable agriculture promoter",
      verified: true,
      contributions: ["Organic Farming", "Soil Health", "Biodiversity"],
    },
    {
      id: "p7",
      name: "Rohan Verma",
      email: "rohan.verma@email.com",
      city: "Hyderabad",
      state: "Telangana",
      ecoPoints: 2340,
      actions: 176,
      joinDate: "2023-05-22",
      avatar: "RV",
      bio: "Tech enthusiast for green solutions",
      verified: true,
      contributions: ["Smart Energy", "IoT Solutions"],
    },
    {
      id: "p8",
      name: "Divya Nair",
      email: "divya.nair@email.com",
      city: "Kochi",
      state: "Kerala",
      ecoPoints: 2950,
      actions: 212,
      joinDate: "2022-09-12",
      avatar: "DN",
      bio: "Marine conservation advocate",
      verified: true,
      contributions: ["Ocean Cleanup", "Marine Life Protection"],
    },
    {
      id: "p9",
      name: "Sanjay Reddy",
      email: "sanjay.reddy@email.com",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      ecoPoints: 1750,
      actions: 128,
      joinDate: "2023-07-03",
      avatar: "SR",
      bio: "Renewable energy consultant",
      verified: true,
      contributions: ["Wind Energy", "Solar Power"],
    },
    {
      id: "p10",
      name: "Meera Iyer",
      email: "meera.iyer@email.com",
      city: "Chennai",
      state: "Tamil Nadu",
      ecoPoints: 2620,
      actions: 189,
      joinDate: "2022-12-01",
      avatar: "MI",
      bio: "Waste reduction and recycling expert",
      verified: true,
      contributions: ["Recycling Programs", "Zero Waste Living"],
    },
    {
      id: "p11",
      name: "Arjun Kapoor",
      email: "arjun.kapoor@email.com",
      city: "Lucknow",
      state: "Uttar Pradesh",
      ecoPoints: 1920,
      actions: 145,
      joinDate: "2023-04-18",
      avatar: "AK",
      bio: "Environmental educator",
      verified: true,
      contributions: ["Education", "Awareness"],
    },
    {
      id: "p12",
      name: "Sneha Bhat",
      email: "sneha.bhat@email.com",
      city: "Bangalore",
      state: "Karnataka",
      ecoPoints: 3200,
      actions: 245,
      joinDate: "2022-08-25",
      avatar: "SB",
      bio: "Sustainable lifestyle blogger",
      verified: true,
      contributions: ["Sustainable Fashion", "Eco-friendly Products"],
    },
  ],

  // Real industries data
  industries: [
    {
      id: "ind1",
      name: "GreenTech Solutions",
      sector: "Technology",
      location: "Bangalore, Karnataka",
      ecoPoints: 15000,
      employees: 450,
      certifications: ["ISO 14001", "B Corp Certified"],
      initiatives: ["Carbon Neutral Operations", "Renewable Energy", "Waste Reduction"],
      verified: true,
      rating: 4.8,
      description: "Leading provider of sustainable technology solutions",
    },
    {
      id: "ind2",
      name: "EcoManufacture Ltd",
      sector: "Manufacturing",
      location: "Pune, Maharashtra",
      ecoPoints: 12500,
      employees: 320,
      certifications: ["ISO 14001", "Green Factory Certified"],
      initiatives: ["Water Recycling", "Energy Efficiency", "Sustainable Materials"],
      verified: true,
      rating: 4.6,
      description: "Sustainable manufacturing with zero-waste commitment",
    },
    {
      id: "ind3",
      name: "Solar Power India",
      sector: "Energy",
      location: "Hyderabad, Telangana",
      ecoPoints: 18000,
      employees: 280,
      certifications: ["ISO 9001", "Renewable Energy Certified"],
      initiatives: ["Solar Installation", "Grid Integration", "Community Projects"],
      verified: true,
      rating: 4.9,
      description: "India's leading solar energy provider",
    },
    {
      id: "ind4",
      name: "Organic Harvest Farms",
      sector: "Agriculture",
      location: "Nashik, Maharashtra",
      ecoPoints: 11000,
      employees: 150,
      certifications: ["Organic Certified", "Fair Trade"],
      initiatives: ["Organic Farming", "Soil Health", "Biodiversity"],
      verified: true,
      rating: 4.7,
      description: "Premium organic agricultural products",
    },
    {
      id: "ind5",
      name: "CleanWater Systems",
      sector: "Water Management",
      location: "Delhi",
      ecoPoints: 13500,
      employees: 200,
      certifications: ["Water Quality Certified", "ISO 14001"],
      initiatives: ["Water Purification", "Rainwater Harvesting", "Wastewater Treatment"],
      verified: true,
      rating: 4.5,
      description: "Advanced water treatment and conservation solutions",
    },
    {
      id: "ind6",
      name: "EcoPackaging Co",
      sector: "Packaging",
      location: "Ahmedabad, Gujarat",
      ecoPoints: 9500,
      employees: 180,
      certifications: ["Eco-Friendly Packaging", "ISO 14001"],
      initiatives: ["Biodegradable Materials", "Recycling Programs"],
      verified: true,
      rating: 4.4,
      description: "Sustainable packaging solutions for businesses",
    },
    {
      id: "ind7",
      name: "Green Building Corp",
      sector: "Construction",
      location: "Mumbai, Maharashtra",
      ecoPoints: 14200,
      employees: 380,
      certifications: ["LEED Certified", "Green Building Certified"],
      initiatives: ["Sustainable Construction", "Energy Efficient Buildings"],
      verified: true,
      rating: 4.8,
      description: "Eco-friendly construction and real estate development",
    },
    {
      id: "ind8",
      name: "Renewable Textiles",
      sector: "Textiles",
      location: "Tiruppur, Tamil Nadu",
      ecoPoints: 10800,
      employees: 220,
      certifications: ["Organic Textile Certified", "Fair Trade"],
      initiatives: ["Sustainable Fabrics", "Waste Reduction", "Water Conservation"],
      verified: true,
      rating: 4.6,
      description: "Sustainable textile manufacturing",
    },
    {
      id: "ind9",
      name: "EcoTransport Solutions",
      sector: "Transportation",
      location: "Bangalore, Karnataka",
      ecoPoints: 12000,
      employees: 290,
      certifications: ["Electric Vehicle Certified", "Carbon Neutral"],
      initiatives: ["EV Fleet", "Route Optimization", "Emission Reduction"],
      verified: true,
      rating: 4.7,
      description: "Sustainable transportation and logistics",
    },
    {
      id: "ind10",
      name: "Green Hospitality Group",
      sector: "Hospitality",
      location: "Goa",
      ecoPoints: 8900,
      employees: 150,
      certifications: ["Green Hotel Certified", "ISO 14001"],
      initiatives: ["Energy Efficiency", "Waste Management", "Community Engagement"],
      verified: true,
      rating: 4.5,
      description: "Eco-friendly hospitality and tourism services",
    },
  ],

  // Real marketplace resources
  resources: [
    {
      id: "r1",
      name: "Recycled Plastic Pellets",
      category: "Raw Materials",
      seller: "EcoManufacture Ltd",
      price: 45,
      quantity: 1000,
      unit: "kg",
      location: "Pune, Maharashtra",
      certified: true,
      rating: 4.8,
      description: "High-quality recycled plastic pellets for manufacturing",
      ecoImpact: "Reduces plastic waste by 500kg per batch",
    },
    {
      id: "r2",
      name: "Organic Fertilizer",
      category: "Agricultural",
      seller: "Organic Harvest Farms",
      price: 25,
      quantity: 50,
      unit: "kg",
      location: "Nashik, Maharashtra",
      certified: true,
      rating: 4.9,
      description: "100% organic fertilizer from composted waste",
      ecoImpact: "Improves soil health and reduces chemical usage",
    },
    {
      id: "r3",
      name: "Solar Panel (500W)",
      category: "Energy",
      seller: "Solar Power India",
      price: 15000,
      quantity: 1,
      unit: "piece",
      location: "Hyderabad, Telangana",
      certified: true,
      rating: 4.9,
      description: "High-efficiency monocrystalline solar panel",
      ecoImpact: "Generates 2000 kWh annually, saves 2 tons CO2/year",
    },
    {
      id: "r4",
      name: "Biodegradable Packaging",
      category: "Packaging",
      seller: "EcoPackaging Co",
      price: 120,
      quantity: 500,
      unit: "pieces",
      location: "Ahmedabad, Gujarat",
      certified: true,
      rating: 4.7,
      description: "100% biodegradable packaging materials",
      ecoImpact: "Reduces plastic waste by 250kg per order",
    },
    {
      id: "r5",
      name: "Water Purification System",
      category: "Water Management",
      seller: "CleanWater Systems",
      price: 8500,
      quantity: 1,
      unit: "piece",
      location: "Delhi",
      certified: true,
      rating: 4.6,
      description: "Advanced water purification for homes and offices",
      ecoImpact: "Saves 10,000 liters of water annually",
    },
    {
      id: "r6",
      name: "Organic Cotton Fabric",
      category: "Textiles",
      seller: "Renewable Textiles",
      price: 350,
      quantity: 10,
      unit: "meters",
      location: "Tiruppur, Tamil Nadu",
      certified: true,
      rating: 4.8,
      description: "Premium organic cotton fabric for apparel",
      ecoImpact: "Uses 91% less water than conventional cotton",
    },
    {
      id: "r7",
      name: "LED Lighting Kit",
      category: "Energy",
      seller: "GreenTech Solutions",
      price: 2500,
      quantity: 1,
      unit: "kit",
      location: "Bangalore, Karnataka",
      certified: true,
      rating: 4.7,
      description: "Complete LED lighting solution for offices",
      ecoImpact: "Reduces energy consumption by 80%",
    },
    {
      id: "r8",
      name: "Rainwater Harvesting Kit",
      category: "Water Management",
      seller: "CleanWater Systems",
      price: 12000,
      quantity: 1,
      unit: "piece",
      location: "Delhi",
      certified: true,
      rating: 4.8,
      description: "Complete rainwater harvesting system",
      ecoImpact: "Collects 50,000 liters annually",
    },
    {
      id: "r9",
      name: "Eco-Friendly Paint",
      category: "Building Materials",
      seller: "Green Building Corp",
      price: 800,
      quantity: 20,
      unit: "liters",
      location: "Mumbai, Maharashtra",
      certified: true,
      rating: 4.6,
      description: "Zero-VOC eco-friendly paint for interiors",
      ecoImpact: "No harmful emissions, safe for health",
    },
    {
      id: "r10",
      name: "Bamboo Flooring",
      category: "Building Materials",
      seller: "Green Building Corp",
      price: 450,
      quantity: 1,
      unit: "sq.meter",
      location: "Mumbai, Maharashtra",
      certified: true,
      rating: 4.9,
      description: "Sustainable bamboo flooring material",
      ecoImpact: "Bamboo grows 35x faster than trees",
    },
  ],

  // Search-friendly data
  searchableData: {
    people: [
      "Rajesh Kumar",
      "Priya Sharma",
      "Amit Patel",
      "Neha Gupta",
      "Vikram Singh",
      "Anjali Desai",
      "Rohan Verma",
      "Divya Nair",
      "Sanjay Reddy",
      "Meera Iyer",
      "Arjun Kapoor",
      "Sneha Bhat",
    ],
    industries: [
      "GreenTech Solutions",
      "EcoManufacture Ltd",
      "Solar Power India",
      "Organic Harvest Farms",
      "CleanWater Systems",
      "EcoPackaging Co",
      "Green Building Corp",
      "Renewable Textiles",
      "EcoTransport Solutions",
      "Green Hospitality Group",
    ],
    states: [
      "Karnataka",
      "Maharashtra",
      "Gujarat",
      "Delhi",
      "Rajasthan",
      "Telangana",
      "Andhra Pradesh",
      "Tamil Nadu",
      "Uttar Pradesh",
      "Kerala",
    ],
    cities: [
      "Bangalore",
      "Mumbai",
      "Ahmedabad",
      "Delhi",
      "Jaipur",
      "Pune",
      "Hyderabad",
      "Kochi",
      "Visakhapatnam",
      "Chennai",
      "Lucknow",
      "Nashik",
      "Tiruppur",
      "Goa",
    ],
  },
}
